// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config11_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_18_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_14_V_read;
input  [15:0] data_15_V_read;
input  [15:0] data_16_V_read;
input  [15:0] data_18_V_read;
input  [15:0] data_20_V_read;
input  [15:0] data_21_V_read;
input  [15:0] data_22_V_read;
input  [15:0] data_23_V_read;
input  [15:0] data_24_V_read;
input  [15:0] data_25_V_read;
input  [15:0] data_26_V_read;
input  [15:0] data_27_V_read;
input  [15:0] data_28_V_read;
input  [15:0] data_29_V_read;
input  [15:0] data_31_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
input   ap_ce;

reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;

reg  signed [15:0] data_31_V_read_4_reg_7131;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] data_16_V_read_4_reg_7136;
reg   [15:0] data_9_V_read_4_reg_7141;
reg  signed [15:0] data_5_V_read_4_reg_7147;
reg   [15:0] data_1_V_read_5_reg_7152;
wire  signed [25:0] sext_ln1118_fu_6323_p1;
wire  signed [25:0] sext_ln1118_2_fu_6329_p1;
wire  signed [25:0] sext_ln1118_3_fu_6335_p1;
wire  signed [25:0] sext_ln1118_4_fu_6341_p1;
wire  signed [25:0] sext_ln1118_7_fu_6352_p1;
wire  signed [25:0] sext_ln1118_15_fu_6383_p1;
wire  signed [25:0] sext_ln1118_21_fu_6409_p1;
wire  signed [25:0] sext_ln1118_23_fu_6420_p1;
wire  signed [25:0] sext_ln1118_24_fu_6426_p1;
wire  signed [25:0] sext_ln1118_25_fu_6432_p1;
wire  signed [25:0] sext_ln1118_27_fu_6443_p1;
reg   [15:0] mult_3_V_reg_7289;
reg   [15:0] mult_4_V_reg_7294;
reg   [15:0] mult_9_V_reg_7299;
reg   [15:0] mult_10_V_reg_7304;
reg   [15:0] mult_13_V_reg_7309;
reg   [15:0] mult_16_V_reg_7314;
reg   [15:0] mult_18_V_reg_7319;
reg   [15:0] mult_23_V_reg_7324;
reg   [15:0] mult_24_V_reg_7329;
reg   [15:0] mult_30_V_reg_7339;
reg   [15:0] mult_38_V_reg_7344;
reg   [15:0] mult_39_V_reg_7349;
reg   [15:0] mult_41_V_reg_7354;
reg   [15:0] mult_49_V_reg_7359;
reg   [15:0] mult_53_V_reg_7364;
reg   [15:0] mult_57_V_reg_7369;
reg   [15:0] mult_64_V_reg_7374;
reg   [15:0] mult_69_V_reg_7379;
reg   [15:0] trunc_ln_reg_7384;
reg   [15:0] trunc_ln708_5_reg_7389;
reg   [15:0] trunc_ln708_6_reg_7394;
reg   [15:0] trunc_ln708_8_reg_7404;
reg   [15:0] trunc_ln708_9_reg_7409;
reg   [15:0] trunc_ln708_s_reg_7414;
reg   [15:0] trunc_ln708_1_reg_7419;
reg   [15:0] trunc_ln708_1_reg_7419_pp0_iter2_reg;
reg   [15:0] trunc_ln708_2_reg_7424;
reg   [15:0] trunc_ln708_3_reg_7429;
reg   [15:0] trunc_ln708_4_reg_7434;
reg   [15:0] trunc_ln708_4_reg_7434_pp0_iter2_reg;
reg   [15:0] trunc_ln708_10_reg_7439;
reg   [15:0] trunc_ln708_11_reg_7444;
reg   [15:0] trunc_ln708_12_reg_7449;
reg   [15:0] trunc_ln708_12_reg_7449_pp0_iter2_reg;
reg   [15:0] trunc_ln708_13_reg_7454;
reg   [15:0] trunc_ln708_14_reg_7459;
reg   [15:0] trunc_ln708_14_reg_7459_pp0_iter2_reg;
reg   [15:0] trunc_ln708_15_reg_7464;
reg   [15:0] trunc_ln708_16_reg_7469;
reg   [15:0] trunc_ln708_17_reg_7474;
reg   [15:0] trunc_ln708_17_reg_7474_pp0_iter2_reg;
reg   [15:0] trunc_ln708_18_reg_7479;
reg   [15:0] mult_29_V_reg_7489;
reg   [15:0] trunc_ln708_7_reg_7494;
reg   [15:0] trunc_ln708_19_reg_7499;
wire   [15:0] add_ln703_1_fu_6928_p2;
reg   [15:0] add_ln703_1_reg_7504;
wire   [15:0] add_ln703_2_fu_6933_p2;
reg   [15:0] add_ln703_2_reg_7509;
wire   [15:0] add_ln703_6_fu_6942_p2;
reg   [15:0] add_ln703_6_reg_7514;
wire   [15:0] add_ln703_7_fu_6947_p2;
reg   [15:0] add_ln703_7_reg_7519;
wire   [15:0] add_ln703_10_fu_6952_p2;
reg   [15:0] add_ln703_10_reg_7524;
wire   [15:0] add_ln703_11_fu_6956_p2;
reg   [15:0] add_ln703_11_reg_7529;
wire   [15:0] add_ln703_15_fu_6965_p2;
reg   [15:0] add_ln703_15_reg_7534;
wire   [15:0] add_ln703_16_fu_6970_p2;
reg   [15:0] add_ln703_16_reg_7539;
wire   [15:0] add_ln703_17_fu_6974_p2;
reg   [15:0] add_ln703_17_reg_7544;
wire   [15:0] add_ln703_20_fu_6978_p2;
reg   [15:0] add_ln703_20_reg_7549;
wire   [15:0] add_ln703_23_fu_6982_p2;
reg   [15:0] add_ln703_23_reg_7554;
wire   [15:0] add_ln703_29_fu_6990_p2;
reg   [15:0] add_ln703_29_reg_7559;
wire   [15:0] add_ln703_30_fu_6995_p2;
reg   [15:0] add_ln703_30_reg_7564;
wire   [15:0] add_ln703_34_fu_7003_p2;
reg   [15:0] add_ln703_34_reg_7569;
reg   [15:0] add_ln703_34_reg_7569_pp0_iter3_reg;
wire   [15:0] add_ln703_35_fu_7008_p2;
reg   [15:0] add_ln703_35_reg_7574;
wire   [15:0] add_ln703_4_fu_7016_p2;
reg   [15:0] add_ln703_4_reg_7579;
wire   [15:0] acc_1_V_fu_7025_p2;
reg   [15:0] acc_1_V_reg_7584;
wire   [15:0] acc_2_V_fu_7034_p2;
reg   [15:0] acc_2_V_reg_7589;
wire   [15:0] add_ln703_19_fu_7043_p2;
reg   [15:0] add_ln703_19_reg_7594;
wire   [15:0] add_ln703_22_fu_7052_p2;
reg   [15:0] add_ln703_22_reg_7599;
wire   [15:0] add_ln703_25_fu_7062_p2;
reg   [15:0] add_ln703_25_reg_7604;
wire   [15:0] add_ln703_32_fu_7071_p2;
reg   [15:0] add_ln703_32_reg_7609;
wire   [15:0] add_ln703_37_fu_7081_p2;
reg   [15:0] add_ln703_37_reg_7614;
wire  signed [15:0] grp_fu_356_p0;
wire  signed [9:0] grp_fu_356_p1;
wire    ap_block_pp0_stage0;
wire   [11:0] grp_fu_357_p1;
wire  signed [15:0] grp_fu_358_p0;
wire  signed [10:0] grp_fu_358_p1;
wire  signed [9:0] grp_fu_359_p1;
wire  signed [15:0] grp_fu_360_p0;
wire  signed [9:0] grp_fu_360_p1;
wire  signed [11:0] grp_fu_361_p1;
wire  signed [11:0] grp_fu_362_p1;
wire  signed [15:0] grp_fu_363_p0;
wire   [11:0] grp_fu_363_p1;
wire  signed [10:0] grp_fu_364_p1;
wire  signed [15:0] grp_fu_365_p0;
wire  signed [10:0] grp_fu_365_p1;
wire  signed [10:0] grp_fu_366_p1;
wire  signed [15:0] grp_fu_367_p0;
wire  signed [10:0] grp_fu_367_p1;
wire  signed [15:0] grp_fu_368_p0;
wire   [10:0] grp_fu_368_p1;
wire  signed [10:0] grp_fu_369_p1;
wire  signed [10:0] grp_fu_370_p1;
wire  signed [15:0] grp_fu_371_p0;
wire  signed [11:0] grp_fu_371_p1;
wire  signed [10:0] grp_fu_372_p1;
wire  signed [15:0] grp_fu_373_p0;
wire  signed [9:0] grp_fu_373_p1;
wire  signed [15:0] grp_fu_374_p0;
wire   [10:0] grp_fu_374_p1;
wire  signed [10:0] grp_fu_375_p1;
wire  signed [9:0] grp_fu_376_p1;
wire  signed [15:0] grp_fu_377_p0;
wire  signed [10:0] grp_fu_377_p1;
wire  signed [15:0] grp_fu_379_p0;
wire  signed [9:0] grp_fu_379_p1;
wire  signed [10:0] grp_fu_380_p1;
wire  signed [15:0] grp_fu_381_p0;
wire   [10:0] grp_fu_381_p1;
wire  signed [15:0] grp_fu_382_p0;
wire   [10:0] grp_fu_382_p1;
wire  signed [15:0] grp_fu_383_p0;
wire   [10:0] grp_fu_383_p1;
wire  signed [10:0] grp_fu_384_p1;
wire  signed [9:0] grp_fu_385_p1;
wire  signed [11:0] grp_fu_386_p1;
wire  signed [11:0] grp_fu_387_p1;
wire  signed [15:0] grp_fu_388_p0;
wire  signed [10:0] grp_fu_388_p1;
wire  signed [15:0] grp_fu_389_p0;
wire  signed [10:0] grp_fu_389_p1;
wire  signed [15:0] grp_fu_390_p0;
wire   [10:0] grp_fu_390_p1;
wire  signed [15:0] grp_fu_392_p0;
wire  signed [9:0] grp_fu_392_p1;
wire  signed [15:0] grp_fu_393_p0;
wire   [9:0] grp_fu_393_p1;
wire  signed [15:0] grp_fu_394_p0;
wire   [10:0] grp_fu_394_p1;
wire  signed [15:0] grp_fu_395_p0;
wire  signed [9:0] grp_fu_395_p1;
wire   [25:0] grp_fu_392_p2;
wire   [25:0] grp_fu_390_p2;
wire   [23:0] shl_ln1118_s_fu_6481_p3;
wire   [25:0] shl_ln_fu_6474_p3;
wire  signed [25:0] sext_ln1118_1_fu_6488_p1;
wire   [25:0] sub_ln1118_fu_6492_p2;
wire   [25:0] grp_fu_363_p2;
wire   [25:0] grp_fu_388_p2;
wire   [25:0] grp_fu_382_p2;
wire   [25:0] grp_fu_377_p2;
wire   [25:0] grp_fu_367_p2;
wire   [25:0] grp_fu_381_p2;
wire   [25:0] grp_fu_370_p2;
wire   [25:0] grp_fu_394_p2;
wire   [25:0] grp_fu_371_p2;
wire   [25:0] grp_fu_376_p2;
wire   [24:0] shl_ln1118_1_fu_6612_p3;
wire  signed [25:0] sext_ln1118_9_fu_6619_p1;
wire   [20:0] shl_ln1118_2_fu_6629_p3;
wire   [25:0] sub_ln1118_1_fu_6623_p2;
wire  signed [25:0] sext_ln1118_10_fu_6636_p1;
wire   [25:0] sub_ln1118_2_fu_6640_p2;
wire   [25:0] grp_fu_359_p2;
wire   [25:0] grp_fu_380_p2;
wire   [25:0] grp_fu_384_p2;
wire   [25:0] grp_fu_366_p2;
wire   [25:0] grp_fu_356_p2;
wire   [25:0] grp_fu_374_p2;
wire   [25:0] grp_fu_372_p2;
wire   [25:0] grp_fu_369_p2;
wire   [25:0] grp_fu_364_p2;
wire   [25:0] grp_fu_386_p2;
wire   [25:0] grp_fu_368_p2;
wire   [25:0] grp_fu_360_p2;
wire   [25:0] grp_fu_361_p2;
wire   [25:0] grp_fu_373_p2;
wire   [25:0] grp_fu_365_p2;
wire   [25:0] grp_fu_358_p2;
wire   [25:0] grp_fu_389_p2;
wire   [25:0] grp_fu_379_p2;
wire   [25:0] grp_fu_393_p2;
wire   [25:0] grp_fu_385_p2;
wire   [25:0] grp_fu_395_p2;
wire   [25:0] grp_fu_383_p2;
wire   [25:0] grp_fu_362_p2;
wire   [25:0] grp_fu_375_p2;
wire   [25:0] grp_fu_357_p2;
wire   [25:0] grp_fu_387_p2;
wire   [15:0] add_ln703_fu_6924_p2;
wire   [15:0] add_ln703_5_fu_6938_p2;
wire   [15:0] add_ln703_14_fu_6961_p2;
wire   [15:0] add_ln703_28_fu_6986_p2;
wire   [15:0] add_ln703_33_fu_6999_p2;
wire   [15:0] add_ln703_3_fu_7012_p2;
wire   [15:0] add_ln703_8_fu_7021_p2;
wire   [15:0] add_ln703_12_fu_7030_p2;
wire   [15:0] add_ln703_18_fu_7039_p2;
wire   [15:0] add_ln703_21_fu_7048_p2;
wire   [15:0] add_ln703_24_fu_7057_p2;
wire   [15:0] add_ln703_31_fu_7067_p2;
wire   [15:0] add_ln703_36_fu_7076_p2;
wire   [15:0] add_ln703_26_fu_7086_p2;
wire   [15:0] add_ln703_38_fu_7095_p2;
wire   [15:0] acc_3_V_fu_7090_p2;
wire   [15:0] acc_4_V_fu_7099_p2;
reg    grp_fu_356_ce;
reg    grp_fu_357_ce;
reg    grp_fu_358_ce;
reg    grp_fu_359_ce;
reg    grp_fu_360_ce;
reg    grp_fu_361_ce;
reg    grp_fu_362_ce;
reg    grp_fu_363_ce;
reg    grp_fu_364_ce;
reg    grp_fu_365_ce;
reg    grp_fu_366_ce;
reg    grp_fu_367_ce;
reg    grp_fu_368_ce;
reg    grp_fu_369_ce;
reg    grp_fu_370_ce;
reg    grp_fu_371_ce;
reg    grp_fu_372_ce;
reg    grp_fu_373_ce;
reg    grp_fu_374_ce;
reg    grp_fu_375_ce;
reg    grp_fu_376_ce;
reg    grp_fu_377_ce;
reg    grp_fu_379_ce;
reg    grp_fu_380_ce;
reg    grp_fu_381_ce;
reg    grp_fu_382_ce;
reg    grp_fu_383_ce;
reg    grp_fu_384_ce;
reg    grp_fu_385_ce;
reg    grp_fu_386_ce;
reg    grp_fu_387_ce;
reg    grp_fu_388_ce;
reg    grp_fu_389_ce;
reg    grp_fu_390_ce;
reg    grp_fu_392_ce;
reg    grp_fu_393_ce;
reg    grp_fu_394_ce;
reg    grp_fu_395_ce;
reg    ap_ce_reg;
reg   [15:0] data_0_V_read_int_reg;
reg   [15:0] data_1_V_read_int_reg;
reg   [15:0] data_2_V_read_int_reg;
reg   [15:0] data_3_V_read_int_reg;
reg   [15:0] data_4_V_read_int_reg;
reg   [15:0] data_5_V_read_int_reg;
reg  signed [15:0] data_6_V_read_int_reg;
reg   [15:0] data_7_V_read_int_reg;
reg  signed [15:0] data_8_V_read_int_reg;
reg   [15:0] data_9_V_read_int_reg;
reg  signed [15:0] data_10_V_read_int_reg;
reg  signed [15:0] data_11_V_read_int_reg;
reg  signed [15:0] data_12_V_read_int_reg;
reg  signed [15:0] data_13_V_read_int_reg;
reg   [15:0] data_14_V_read_int_reg;
reg  signed [15:0] data_15_V_read_int_reg;
reg   [15:0] data_16_V_read_int_reg;
reg  signed [15:0] data_18_V_read_int_reg;
reg  signed [15:0] data_20_V_read_int_reg;
reg  signed [15:0] data_21_V_read_int_reg;
reg   [15:0] data_22_V_read_int_reg;
reg  signed [15:0] data_23_V_read_int_reg;
reg   [15:0] data_24_V_read_int_reg;
reg   [15:0] data_25_V_read_int_reg;
reg   [15:0] data_26_V_read_int_reg;
reg  signed [15:0] data_27_V_read_int_reg;
reg   [15:0] data_28_V_read_int_reg;
reg  signed [15:0] data_29_V_read_int_reg;
reg   [15:0] data_31_V_read_int_reg;
reg   [15:0] ap_return_0_int_reg;
reg   [15:0] ap_return_1_int_reg;
reg   [15:0] ap_return_2_int_reg;
reg   [15:0] ap_return_3_int_reg;
reg   [15:0] ap_return_4_int_reg;

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1126(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_356_p0),
    .din1(grp_fu_356_p1),
    .ce(grp_fu_356_ce),
    .dout(grp_fu_356_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12ns_26_2_0_U1127(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_16_V_read_4_reg_7136),
    .din1(grp_fu_357_p1),
    .ce(grp_fu_357_ce),
    .dout(grp_fu_357_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1128(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_358_p0),
    .din1(grp_fu_358_p1),
    .ce(grp_fu_358_ce),
    .dout(grp_fu_358_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1129(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_10_V_read_int_reg),
    .din1(grp_fu_359_p1),
    .ce(grp_fu_359_ce),
    .dout(grp_fu_359_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1130(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_360_p0),
    .din1(grp_fu_360_p1),
    .ce(grp_fu_360_ce),
    .dout(grp_fu_360_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12s_26_2_0_U1131(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_23_V_read_int_reg),
    .din1(grp_fu_361_p1),
    .ce(grp_fu_361_ce),
    .dout(grp_fu_361_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12s_26_2_0_U1132(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_29_V_read_int_reg),
    .din1(grp_fu_362_p1),
    .ce(grp_fu_362_ce),
    .dout(grp_fu_362_p2)
);

myproject_mul_16s_12ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12ns_26_2_0_U1133(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_363_p0),
    .din1(grp_fu_363_p1),
    .ce(grp_fu_363_ce),
    .dout(grp_fu_363_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1134(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_20_V_read_int_reg),
    .din1(grp_fu_364_p1),
    .ce(grp_fu_364_ce),
    .dout(grp_fu_364_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1135(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_365_p0),
    .din1(grp_fu_365_p1),
    .ce(grp_fu_365_ce),
    .dout(grp_fu_365_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1136(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_13_V_read_int_reg),
    .din1(grp_fu_366_p1),
    .ce(grp_fu_366_ce),
    .dout(grp_fu_366_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1137(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_367_p0),
    .din1(grp_fu_367_p1),
    .ce(grp_fu_367_ce),
    .dout(grp_fu_367_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1138(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_368_p0),
    .din1(grp_fu_368_p1),
    .ce(grp_fu_368_ce),
    .dout(grp_fu_368_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1139(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_18_V_read_int_reg),
    .din1(grp_fu_369_p1),
    .ce(grp_fu_369_ce),
    .dout(grp_fu_369_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_6_V_read_int_reg),
    .din1(grp_fu_370_p1),
    .ce(grp_fu_370_ce),
    .dout(grp_fu_370_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12s_26_2_0_U1141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_371_p0),
    .din1(grp_fu_371_p1),
    .ce(grp_fu_371_ce),
    .dout(grp_fu_371_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_15_V_read_int_reg),
    .din1(grp_fu_372_p1),
    .ce(grp_fu_372_ce),
    .dout(grp_fu_372_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1143(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_373_p0),
    .din1(grp_fu_373_p1),
    .ce(grp_fu_373_ce),
    .dout(grp_fu_373_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1144(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_374_p0),
    .din1(grp_fu_374_p1),
    .ce(grp_fu_374_ce),
    .dout(grp_fu_374_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1145(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_5_V_read_4_reg_7147),
    .din1(grp_fu_375_p1),
    .ce(grp_fu_375_ce),
    .dout(grp_fu_375_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1146(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_8_V_read_int_reg),
    .din1(grp_fu_376_p1),
    .ce(grp_fu_376_ce),
    .dout(grp_fu_376_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1147(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_377_p0),
    .din1(grp_fu_377_p1),
    .ce(grp_fu_377_ce),
    .dout(grp_fu_377_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1148(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_379_p0),
    .din1(grp_fu_379_p1),
    .ce(grp_fu_379_ce),
    .dout(grp_fu_379_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1149(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_11_V_read_int_reg),
    .din1(grp_fu_380_p1),
    .ce(grp_fu_380_ce),
    .dout(grp_fu_380_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1150(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_381_p0),
    .din1(grp_fu_381_p1),
    .ce(grp_fu_381_ce),
    .dout(grp_fu_381_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1151(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_382_p0),
    .din1(grp_fu_382_p1),
    .ce(grp_fu_382_ce),
    .dout(grp_fu_382_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1152(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_383_p0),
    .din1(grp_fu_383_p1),
    .ce(grp_fu_383_ce),
    .dout(grp_fu_383_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1153(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_12_V_read_int_reg),
    .din1(grp_fu_384_p1),
    .ce(grp_fu_384_ce),
    .dout(grp_fu_384_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1154(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_27_V_read_int_reg),
    .din1(grp_fu_385_p1),
    .ce(grp_fu_385_ce),
    .dout(grp_fu_385_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12s_26_2_0_U1155(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_21_V_read_int_reg),
    .din1(grp_fu_386_p1),
    .ce(grp_fu_386_ce),
    .dout(grp_fu_386_p2)
);

myproject_mul_16s_12s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_12s_26_2_0_U1156(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(data_31_V_read_4_reg_7131),
    .din1(grp_fu_387_p1),
    .ce(grp_fu_387_ce),
    .dout(grp_fu_387_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1157(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_388_p0),
    .din1(grp_fu_388_p1),
    .ce(grp_fu_388_ce),
    .dout(grp_fu_388_p2)
);

myproject_mul_16s_11s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11s_26_2_0_U1158(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_389_p0),
    .din1(grp_fu_389_p1),
    .ce(grp_fu_389_ce),
    .dout(grp_fu_389_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1159(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_390_p0),
    .din1(grp_fu_390_p1),
    .ce(grp_fu_390_ce),
    .dout(grp_fu_390_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1160(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_392_p0),
    .din1(grp_fu_392_p1),
    .ce(grp_fu_392_ce),
    .dout(grp_fu_392_p2)
);

myproject_mul_16s_10ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10ns_26_2_0_U1161(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_393_p0),
    .din1(grp_fu_393_p1),
    .ce(grp_fu_393_ce),
    .dout(grp_fu_393_p2)
);

myproject_mul_16s_11ns_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_11ns_26_2_0_U1162(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_394_p0),
    .din1(grp_fu_394_p1),
    .ce(grp_fu_394_ce),
    .dout(grp_fu_394_p2)
);

myproject_mul_16s_10s_26_2_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
myproject_mul_16s_10s_26_2_0_U1163(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_395_p0),
    .din1(grp_fu_395_p1),
    .ce(grp_fu_395_ce),
    .dout(grp_fu_395_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce_reg) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        acc_1_V_reg_7584 <= acc_1_V_fu_7025_p2;
        acc_2_V_reg_7589 <= acc_2_V_fu_7034_p2;
        add_ln703_10_reg_7524 <= add_ln703_10_fu_6952_p2;
        add_ln703_11_reg_7529 <= add_ln703_11_fu_6956_p2;
        add_ln703_15_reg_7534 <= add_ln703_15_fu_6965_p2;
        add_ln703_16_reg_7539 <= add_ln703_16_fu_6970_p2;
        add_ln703_17_reg_7544 <= add_ln703_17_fu_6974_p2;
        add_ln703_19_reg_7594 <= add_ln703_19_fu_7043_p2;
        add_ln703_1_reg_7504 <= add_ln703_1_fu_6928_p2;
        add_ln703_20_reg_7549 <= add_ln703_20_fu_6978_p2;
        add_ln703_22_reg_7599 <= add_ln703_22_fu_7052_p2;
        add_ln703_23_reg_7554 <= add_ln703_23_fu_6982_p2;
        add_ln703_25_reg_7604 <= add_ln703_25_fu_7062_p2;
        add_ln703_29_reg_7559 <= add_ln703_29_fu_6990_p2;
        add_ln703_2_reg_7509 <= add_ln703_2_fu_6933_p2;
        add_ln703_30_reg_7564 <= add_ln703_30_fu_6995_p2;
        add_ln703_32_reg_7609 <= add_ln703_32_fu_7071_p2;
        add_ln703_34_reg_7569 <= add_ln703_34_fu_7003_p2;
        add_ln703_34_reg_7569_pp0_iter3_reg <= add_ln703_34_reg_7569;
        add_ln703_35_reg_7574 <= add_ln703_35_fu_7008_p2;
        add_ln703_37_reg_7614 <= add_ln703_37_fu_7081_p2;
        add_ln703_4_reg_7579 <= add_ln703_4_fu_7016_p2;
        add_ln703_6_reg_7514 <= add_ln703_6_fu_6942_p2;
        add_ln703_7_reg_7519 <= add_ln703_7_fu_6947_p2;
        data_16_V_read_4_reg_7136 <= data_16_V_read_int_reg;
        data_1_V_read_5_reg_7152 <= data_1_V_read_int_reg;
        data_31_V_read_4_reg_7131 <= data_31_V_read_int_reg;
        data_5_V_read_4_reg_7147 <= data_5_V_read_int_reg;
        data_9_V_read_4_reg_7141 <= data_9_V_read_int_reg;
        mult_10_V_reg_7304 <= {{grp_fu_363_p2[25:10]}};
        mult_13_V_reg_7309 <= {{grp_fu_388_p2[25:10]}};
        mult_16_V_reg_7314 <= {{grp_fu_382_p2[25:10]}};
        mult_18_V_reg_7319 <= {{grp_fu_377_p2[25:10]}};
        mult_23_V_reg_7324 <= {{grp_fu_367_p2[25:10]}};
        mult_24_V_reg_7329 <= {{grp_fu_381_p2[25:10]}};
        mult_29_V_reg_7489 <= {{grp_fu_375_p2[25:10]}};
        mult_30_V_reg_7339 <= {{grp_fu_370_p2[25:10]}};
        mult_38_V_reg_7344 <= {{grp_fu_394_p2[25:10]}};
        mult_39_V_reg_7349 <= {{grp_fu_371_p2[25:10]}};
        mult_3_V_reg_7289 <= {{grp_fu_392_p2[25:10]}};
        mult_41_V_reg_7354 <= {{grp_fu_376_p2[25:10]}};
        mult_49_V_reg_7359 <= {{sub_ln1118_2_fu_6640_p2[25:10]}};
        mult_4_V_reg_7294 <= {{grp_fu_390_p2[25:10]}};
        mult_53_V_reg_7364 <= {{grp_fu_359_p2[25:10]}};
        mult_57_V_reg_7369 <= {{grp_fu_380_p2[25:10]}};
        mult_64_V_reg_7374 <= {{grp_fu_384_p2[25:10]}};
        mult_69_V_reg_7379 <= {{grp_fu_366_p2[25:10]}};
        mult_9_V_reg_7299 <= {{sub_ln1118_fu_6492_p2[25:10]}};
        trunc_ln708_10_reg_7439 <= {{grp_fu_365_p2[25:10]}};
        trunc_ln708_11_reg_7444 <= {{grp_fu_358_p2[25:10]}};
        trunc_ln708_12_reg_7449 <= {{grp_fu_389_p2[25:10]}};
        trunc_ln708_12_reg_7449_pp0_iter2_reg <= trunc_ln708_12_reg_7449;
        trunc_ln708_13_reg_7454 <= {{grp_fu_379_p2[25:10]}};
        trunc_ln708_14_reg_7459 <= {{grp_fu_393_p2[25:10]}};
        trunc_ln708_14_reg_7459_pp0_iter2_reg <= trunc_ln708_14_reg_7459;
        trunc_ln708_15_reg_7464 <= {{grp_fu_385_p2[25:10]}};
        trunc_ln708_16_reg_7469 <= {{grp_fu_395_p2[25:10]}};
        trunc_ln708_17_reg_7474 <= {{grp_fu_383_p2[25:10]}};
        trunc_ln708_17_reg_7474_pp0_iter2_reg <= trunc_ln708_17_reg_7474;
        trunc_ln708_18_reg_7479 <= {{grp_fu_362_p2[25:10]}};
        trunc_ln708_19_reg_7499 <= {{grp_fu_387_p2[25:10]}};
        trunc_ln708_1_reg_7419 <= {{grp_fu_368_p2[25:10]}};
        trunc_ln708_1_reg_7419_pp0_iter2_reg <= trunc_ln708_1_reg_7419;
        trunc_ln708_2_reg_7424 <= {{grp_fu_360_p2[25:10]}};
        trunc_ln708_3_reg_7429 <= {{grp_fu_361_p2[25:10]}};
        trunc_ln708_4_reg_7434 <= {{grp_fu_373_p2[25:10]}};
        trunc_ln708_4_reg_7434_pp0_iter2_reg <= trunc_ln708_4_reg_7434;
        trunc_ln708_5_reg_7389 <= {{grp_fu_374_p2[25:10]}};
        trunc_ln708_6_reg_7394 <= {{grp_fu_372_p2[25:10]}};
        trunc_ln708_7_reg_7494 <= {{grp_fu_357_p2[25:10]}};
        trunc_ln708_8_reg_7404 <= {{grp_fu_369_p2[25:10]}};
        trunc_ln708_9_reg_7409 <= {{grp_fu_364_p2[25:10]}};
        trunc_ln708_s_reg_7414 <= {{grp_fu_386_p2[25:10]}};
        trunc_ln_reg_7384 <= {{grp_fu_356_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= add_ln703_4_reg_7579;
        ap_return_1_int_reg <= acc_1_V_reg_7584;
        ap_return_2_int_reg <= acc_2_V_reg_7589;
        ap_return_3_int_reg <= acc_3_V_fu_7090_p2;
        ap_return_4_int_reg <= acc_4_V_fu_7099_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        data_0_V_read_int_reg <= data_0_V_read;
        data_10_V_read_int_reg <= data_10_V_read;
        data_11_V_read_int_reg <= data_11_V_read;
        data_12_V_read_int_reg <= data_12_V_read;
        data_13_V_read_int_reg <= data_13_V_read;
        data_14_V_read_int_reg <= data_14_V_read;
        data_15_V_read_int_reg <= data_15_V_read;
        data_16_V_read_int_reg <= data_16_V_read;
        data_18_V_read_int_reg <= data_18_V_read;
        data_1_V_read_int_reg <= data_1_V_read;
        data_20_V_read_int_reg <= data_20_V_read;
        data_21_V_read_int_reg <= data_21_V_read;
        data_22_V_read_int_reg <= data_22_V_read;
        data_23_V_read_int_reg <= data_23_V_read;
        data_24_V_read_int_reg <= data_24_V_read;
        data_25_V_read_int_reg <= data_25_V_read;
        data_26_V_read_int_reg <= data_26_V_read;
        data_27_V_read_int_reg <= data_27_V_read;
        data_28_V_read_int_reg <= data_28_V_read;
        data_29_V_read_int_reg <= data_29_V_read;
        data_2_V_read_int_reg <= data_2_V_read;
        data_31_V_read_int_reg <= data_31_V_read;
        data_3_V_read_int_reg <= data_3_V_read;
        data_4_V_read_int_reg <= data_4_V_read;
        data_5_V_read_int_reg <= data_5_V_read;
        data_6_V_read_int_reg <= data_6_V_read;
        data_7_V_read_int_reg <= data_7_V_read;
        data_8_V_read_int_reg <= data_8_V_read;
        data_9_V_read_int_reg <= data_9_V_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = add_ln703_4_reg_7579;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = acc_1_V_reg_7584;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = acc_2_V_reg_7589;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = acc_3_V_fu_7090_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = acc_4_V_fu_7099_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_356_ce = 1'b1;
    end else begin
        grp_fu_356_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_357_ce = 1'b1;
    end else begin
        grp_fu_357_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_358_ce = 1'b1;
    end else begin
        grp_fu_358_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_359_ce = 1'b1;
    end else begin
        grp_fu_359_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_360_ce = 1'b1;
    end else begin
        grp_fu_360_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_361_ce = 1'b1;
    end else begin
        grp_fu_361_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_362_ce = 1'b1;
    end else begin
        grp_fu_362_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_363_ce = 1'b1;
    end else begin
        grp_fu_363_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_364_ce = 1'b1;
    end else begin
        grp_fu_364_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_365_ce = 1'b1;
    end else begin
        grp_fu_365_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_366_ce = 1'b1;
    end else begin
        grp_fu_366_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_367_ce = 1'b1;
    end else begin
        grp_fu_367_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_368_ce = 1'b1;
    end else begin
        grp_fu_368_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_369_ce = 1'b1;
    end else begin
        grp_fu_369_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_370_ce = 1'b1;
    end else begin
        grp_fu_370_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_371_ce = 1'b1;
    end else begin
        grp_fu_371_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_372_ce = 1'b1;
    end else begin
        grp_fu_372_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_373_ce = 1'b1;
    end else begin
        grp_fu_373_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_374_ce = 1'b1;
    end else begin
        grp_fu_374_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_375_ce = 1'b1;
    end else begin
        grp_fu_375_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_376_ce = 1'b1;
    end else begin
        grp_fu_376_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_377_ce = 1'b1;
    end else begin
        grp_fu_377_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_379_ce = 1'b1;
    end else begin
        grp_fu_379_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_380_ce = 1'b1;
    end else begin
        grp_fu_380_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_381_ce = 1'b1;
    end else begin
        grp_fu_381_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_382_ce = 1'b1;
    end else begin
        grp_fu_382_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_383_ce = 1'b1;
    end else begin
        grp_fu_383_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_384_ce = 1'b1;
    end else begin
        grp_fu_384_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_385_ce = 1'b1;
    end else begin
        grp_fu_385_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_386_ce = 1'b1;
    end else begin
        grp_fu_386_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_387_ce = 1'b1;
    end else begin
        grp_fu_387_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_388_ce = 1'b1;
    end else begin
        grp_fu_388_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_389_ce = 1'b1;
    end else begin
        grp_fu_389_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_390_ce = 1'b1;
    end else begin
        grp_fu_390_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_392_ce = 1'b1;
    end else begin
        grp_fu_392_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_393_ce = 1'b1;
    end else begin
        grp_fu_393_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_394_ce = 1'b1;
    end else begin
        grp_fu_394_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_395_ce = 1'b1;
    end else begin
        grp_fu_395_ce = 1'b0;
    end
end

assign acc_1_V_fu_7025_p2 = (add_ln703_6_reg_7514 + add_ln703_8_fu_7021_p2);

assign acc_2_V_fu_7034_p2 = (add_ln703_10_reg_7524 + add_ln703_12_fu_7030_p2);

assign acc_3_V_fu_7090_p2 = (add_ln703_19_reg_7594 + add_ln703_26_fu_7086_p2);

assign acc_4_V_fu_7099_p2 = (add_ln703_32_reg_7609 + add_ln703_38_fu_7095_p2);

assign add_ln703_10_fu_6952_p2 = (trunc_ln_reg_7384 + mult_57_V_reg_7369);

assign add_ln703_11_fu_6956_p2 = (trunc_ln708_18_reg_7479 + 16'd143);

assign add_ln703_12_fu_7030_p2 = (trunc_ln708_7_reg_7494 + add_ln703_11_reg_7529);

assign add_ln703_14_fu_6961_p2 = (mult_18_V_reg_7319 + mult_13_V_reg_7309);

assign add_ln703_15_fu_6965_p2 = (mult_3_V_reg_7289 + add_ln703_14_fu_6961_p2);

assign add_ln703_16_fu_6970_p2 = (mult_38_V_reg_7344 + mult_23_V_reg_7324);

assign add_ln703_17_fu_6974_p2 = (trunc_ln708_5_reg_7389 + mult_53_V_reg_7364);

assign add_ln703_18_fu_7039_p2 = (add_ln703_16_reg_7539 + add_ln703_17_reg_7544);

assign add_ln703_19_fu_7043_p2 = (add_ln703_15_reg_7534 + add_ln703_18_fu_7039_p2);

assign add_ln703_1_fu_6928_p2 = (mult_10_V_reg_7304 + add_ln703_fu_6924_p2);

assign add_ln703_20_fu_6978_p2 = (trunc_ln708_s_reg_7414 + trunc_ln708_6_reg_7394);

assign add_ln703_21_fu_7048_p2 = (trunc_ln708_14_reg_7459_pp0_iter2_reg + trunc_ln708_4_reg_7434_pp0_iter2_reg);

assign add_ln703_22_fu_7052_p2 = (add_ln703_20_reg_7549 + add_ln703_21_fu_7048_p2);

assign add_ln703_23_fu_6982_p2 = (trunc_ln708_16_reg_7469 + trunc_ln708_15_reg_7464);

assign add_ln703_24_fu_7057_p2 = (trunc_ln708_19_reg_7499 + 16'd111);

assign add_ln703_25_fu_7062_p2 = (add_ln703_23_reg_7554 + add_ln703_24_fu_7057_p2);

assign add_ln703_26_fu_7086_p2 = (add_ln703_22_reg_7599 + add_ln703_25_reg_7604);

assign add_ln703_28_fu_6986_p2 = (mult_24_V_reg_7329 + mult_9_V_reg_7299);

assign add_ln703_29_fu_6990_p2 = (mult_4_V_reg_7294 + add_ln703_28_fu_6986_p2);

assign add_ln703_2_fu_6933_p2 = ($signed(trunc_ln708_11_reg_7444) + $signed(16'd65394));

assign add_ln703_30_fu_6995_p2 = (mult_49_V_reg_7359 + mult_39_V_reg_7349);

assign add_ln703_31_fu_7067_p2 = (mult_29_V_reg_7489 + add_ln703_30_reg_7564);

assign add_ln703_32_fu_7071_p2 = (add_ln703_29_reg_7559 + add_ln703_31_fu_7067_p2);

assign add_ln703_33_fu_6999_p2 = (trunc_ln708_8_reg_7404 + mult_69_V_reg_7379);

assign add_ln703_34_fu_7003_p2 = (mult_64_V_reg_7374 + add_ln703_33_fu_6999_p2);

assign add_ln703_35_fu_7008_p2 = (trunc_ln708_10_reg_7439 + trunc_ln708_3_reg_7429);

assign add_ln703_36_fu_7076_p2 = ($signed(trunc_ln708_17_reg_7474_pp0_iter2_reg) + $signed(16'd65481));

assign add_ln703_37_fu_7081_p2 = (add_ln703_35_reg_7574 + add_ln703_36_fu_7076_p2);

assign add_ln703_38_fu_7095_p2 = (add_ln703_34_reg_7569_pp0_iter3_reg + add_ln703_37_reg_7614);

assign add_ln703_3_fu_7012_p2 = (trunc_ln708_1_reg_7419_pp0_iter2_reg + add_ln703_2_reg_7509);

assign add_ln703_4_fu_7016_p2 = (add_ln703_1_reg_7504 + add_ln703_3_fu_7012_p2);

assign add_ln703_5_fu_6938_p2 = (trunc_ln708_2_reg_7424 + mult_41_V_reg_7354);

assign add_ln703_6_fu_6942_p2 = (mult_16_V_reg_7314 + add_ln703_5_fu_6938_p2);

assign add_ln703_7_fu_6947_p2 = ($signed(trunc_ln708_13_reg_7454) + $signed(16'd65451));

assign add_ln703_8_fu_7021_p2 = (trunc_ln708_12_reg_7449_pp0_iter2_reg + add_ln703_7_reg_7519);

assign add_ln703_fu_6924_p2 = (trunc_ln708_9_reg_7409 + mult_30_V_reg_7339);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign grp_fu_356_p0 = sext_ln1118_15_fu_6383_p1;

assign grp_fu_356_p1 = 26'd67108473;

assign grp_fu_357_p1 = 26'd1060;

assign grp_fu_358_p0 = sext_ln1118_24_fu_6426_p1;

assign grp_fu_358_p1 = 26'd67108285;

assign grp_fu_359_p1 = 26'd67108359;

assign grp_fu_360_p0 = sext_ln1118_21_fu_6409_p1;

assign grp_fu_360_p1 = 26'd67108478;

assign grp_fu_361_p1 = 26'd67107675;

assign grp_fu_362_p1 = 26'd67107822;

assign grp_fu_363_p0 = sext_ln1118_2_fu_6329_p1;

assign grp_fu_363_p1 = 26'd1109;

assign grp_fu_364_p1 = 26'd67108043;

assign grp_fu_365_p0 = sext_ln1118_23_fu_6420_p1;

assign grp_fu_365_p1 = 26'd67107887;

assign grp_fu_366_p1 = 26'd67108202;

assign grp_fu_367_p0 = sext_ln1118_4_fu_6341_p1;

assign grp_fu_367_p1 = 26'd67108134;

assign grp_fu_368_p0 = sext_ln1118_21_fu_6409_p1;

assign grp_fu_368_p1 = 26'd594;

assign grp_fu_369_p1 = 26'd67108081;

assign grp_fu_370_p1 = 26'd67108175;

assign grp_fu_371_p0 = sext_ln1118_7_fu_6352_p1;

assign grp_fu_371_p1 = 26'd67107564;

assign grp_fu_372_p1 = 26'd67108172;

assign grp_fu_373_p0 = sext_ln1118_23_fu_6420_p1;

assign grp_fu_373_p1 = 26'd67108357;

assign grp_fu_374_p0 = sext_ln1118_15_fu_6383_p1;

assign grp_fu_374_p1 = 26'd618;

assign grp_fu_375_p1 = 26'd67107979;

assign grp_fu_376_p1 = 26'd67108436;

assign grp_fu_377_p0 = sext_ln1118_3_fu_6335_p1;

assign grp_fu_377_p1 = 26'd67108303;

assign grp_fu_379_p0 = sext_ln1118_25_fu_6432_p1;

assign grp_fu_379_p1 = 26'd67108398;

assign grp_fu_380_p1 = 26'd67108084;

assign grp_fu_381_p0 = sext_ln1118_4_fu_6341_p1;

assign grp_fu_381_p1 = 26'd732;

assign grp_fu_382_p0 = sext_ln1118_3_fu_6335_p1;

assign grp_fu_382_p1 = 26'd566;

assign grp_fu_383_p0 = sext_ln1118_27_fu_6443_p1;

assign grp_fu_383_p1 = 26'd844;

assign grp_fu_384_p1 = 26'd67108343;

assign grp_fu_385_p1 = 26'd67108436;

assign grp_fu_386_p1 = 26'd67107736;

assign grp_fu_387_p1 = 26'd67107512;

assign grp_fu_388_p0 = sext_ln1118_2_fu_6329_p1;

assign grp_fu_388_p1 = 26'd67108239;

assign grp_fu_389_p0 = sext_ln1118_24_fu_6426_p1;

assign grp_fu_389_p1 = 26'd67108250;

assign grp_fu_390_p0 = sext_ln1118_fu_6323_p1;

assign grp_fu_390_p1 = 26'd828;

assign grp_fu_392_p0 = sext_ln1118_fu_6323_p1;

assign grp_fu_392_p1 = 26'd67108393;

assign grp_fu_393_p0 = sext_ln1118_25_fu_6432_p1;

assign grp_fu_393_p1 = 26'd501;

assign grp_fu_394_p0 = sext_ln1118_7_fu_6352_p1;

assign grp_fu_394_p1 = 26'd714;

assign grp_fu_395_p0 = sext_ln1118_27_fu_6443_p1;

assign grp_fu_395_p1 = 26'd67108393;

assign sext_ln1118_10_fu_6636_p1 = $signed(shl_ln1118_2_fu_6629_p3);

assign sext_ln1118_15_fu_6383_p1 = $signed(data_14_V_read_int_reg);

assign sext_ln1118_1_fu_6488_p1 = $signed(shl_ln1118_s_fu_6481_p3);

assign sext_ln1118_21_fu_6409_p1 = $signed(data_22_V_read_int_reg);

assign sext_ln1118_23_fu_6420_p1 = $signed(data_24_V_read_int_reg);

assign sext_ln1118_24_fu_6426_p1 = $signed(data_25_V_read_int_reg);

assign sext_ln1118_25_fu_6432_p1 = $signed(data_26_V_read_int_reg);

assign sext_ln1118_27_fu_6443_p1 = $signed(data_28_V_read_int_reg);

assign sext_ln1118_2_fu_6329_p1 = $signed(data_2_V_read_int_reg);

assign sext_ln1118_3_fu_6335_p1 = $signed(data_3_V_read_int_reg);

assign sext_ln1118_4_fu_6341_p1 = $signed(data_4_V_read_int_reg);

assign sext_ln1118_7_fu_6352_p1 = $signed(data_7_V_read_int_reg);

assign sext_ln1118_9_fu_6619_p1 = $signed(shl_ln1118_1_fu_6612_p3);

assign sext_ln1118_fu_6323_p1 = $signed(data_0_V_read_int_reg);

assign shl_ln1118_1_fu_6612_p3 = {{data_9_V_read_4_reg_7141}, {9'd0}};

assign shl_ln1118_2_fu_6629_p3 = {{data_9_V_read_4_reg_7141}, {5'd0}};

assign shl_ln1118_s_fu_6481_p3 = {{data_1_V_read_5_reg_7152}, {8'd0}};

assign shl_ln_fu_6474_p3 = {{data_1_V_read_5_reg_7152}, {10'd0}};

assign sub_ln1118_1_fu_6623_p2 = ($signed(26'd0) - $signed(sext_ln1118_9_fu_6619_p1));

assign sub_ln1118_2_fu_6640_p2 = ($signed(sub_ln1118_1_fu_6623_p2) - $signed(sext_ln1118_10_fu_6636_p1));

assign sub_ln1118_fu_6492_p2 = ($signed(shl_ln_fu_6474_p3) - $signed(sext_ln1118_1_fu_6488_p1));

endmodule //dense_latency_ap_fixed_ap_fixed_16_6_5_3_0_config11_0_0_0_0_0_0
