Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'pruned_jet_tagging_model/hls4ml_prj/keras_model.keras'
OutputDir: pruned_jet_tagging_model/hls4ml_prj
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: 1a286811
Version: 1.0.0
WriterConfig:
  Namespace: null
  WriteTar: false
  WriteWeightsTxt: true
