// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30
);


output   ap_ready;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_15_V_read;
input  [15:0] data_16_V_read;
input  [15:0] data_17_V_read;
input  [15:0] data_18_V_read;
input  [15:0] data_19_V_read;
input  [15:0] data_20_V_read;
input  [15:0] data_21_V_read;
input  [15:0] data_22_V_read;
input  [15:0] data_23_V_read;
input  [15:0] data_24_V_read;
input  [15:0] data_25_V_read;
input  [15:0] data_26_V_read;
input  [15:0] data_27_V_read;
input  [15:0] data_28_V_read;
input  [15:0] data_29_V_read;
input  [15:0] data_30_V_read;
input  [15:0] data_31_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;

wire   [0:0] icmp_ln1494_fu_266_p2;
wire   [14:0] trunc_ln45_fu_272_p1;
wire   [14:0] select_ln45_fu_276_p3;
wire   [0:0] icmp_ln1494_1_fu_288_p2;
wire   [14:0] trunc_ln45_1_fu_294_p1;
wire   [14:0] select_ln45_1_fu_298_p3;
wire   [0:0] icmp_ln1494_2_fu_310_p2;
wire   [14:0] trunc_ln45_2_fu_316_p1;
wire   [14:0] select_ln45_2_fu_320_p3;
wire   [0:0] icmp_ln1494_3_fu_332_p2;
wire   [14:0] trunc_ln45_3_fu_338_p1;
wire   [14:0] select_ln45_3_fu_342_p3;
wire   [0:0] icmp_ln1494_4_fu_354_p2;
wire   [14:0] trunc_ln45_4_fu_360_p1;
wire   [14:0] select_ln45_4_fu_364_p3;
wire   [0:0] icmp_ln1494_5_fu_376_p2;
wire   [14:0] trunc_ln45_5_fu_382_p1;
wire   [14:0] select_ln45_5_fu_386_p3;
wire   [0:0] icmp_ln1494_6_fu_398_p2;
wire   [14:0] trunc_ln45_6_fu_404_p1;
wire   [14:0] select_ln45_6_fu_408_p3;
wire   [0:0] icmp_ln1494_7_fu_420_p2;
wire   [14:0] trunc_ln45_7_fu_426_p1;
wire   [14:0] select_ln45_7_fu_430_p3;
wire   [0:0] icmp_ln1494_8_fu_442_p2;
wire   [14:0] trunc_ln45_8_fu_448_p1;
wire   [14:0] select_ln45_8_fu_452_p3;
wire   [0:0] icmp_ln1494_9_fu_464_p2;
wire   [14:0] trunc_ln45_9_fu_470_p1;
wire   [14:0] select_ln45_9_fu_474_p3;
wire   [0:0] icmp_ln1494_10_fu_486_p2;
wire   [14:0] trunc_ln45_10_fu_492_p1;
wire   [14:0] select_ln45_10_fu_496_p3;
wire   [0:0] icmp_ln1494_11_fu_508_p2;
wire   [14:0] trunc_ln45_11_fu_514_p1;
wire   [14:0] select_ln45_11_fu_518_p3;
wire   [0:0] icmp_ln1494_12_fu_530_p2;
wire   [14:0] trunc_ln45_12_fu_536_p1;
wire   [14:0] select_ln45_12_fu_540_p3;
wire   [0:0] icmp_ln1494_13_fu_552_p2;
wire   [14:0] trunc_ln45_13_fu_558_p1;
wire   [14:0] select_ln45_13_fu_562_p3;
wire   [0:0] icmp_ln1494_14_fu_574_p2;
wire   [14:0] trunc_ln45_14_fu_580_p1;
wire   [14:0] select_ln45_14_fu_584_p3;
wire   [0:0] icmp_ln1494_15_fu_596_p2;
wire   [14:0] trunc_ln45_15_fu_602_p1;
wire   [14:0] select_ln45_15_fu_606_p3;
wire   [0:0] icmp_ln1494_16_fu_618_p2;
wire   [14:0] trunc_ln45_16_fu_624_p1;
wire   [14:0] select_ln45_16_fu_628_p3;
wire   [0:0] icmp_ln1494_17_fu_640_p2;
wire   [14:0] trunc_ln45_17_fu_646_p1;
wire   [14:0] select_ln45_17_fu_650_p3;
wire   [0:0] icmp_ln1494_18_fu_662_p2;
wire   [14:0] trunc_ln45_18_fu_668_p1;
wire   [14:0] select_ln45_18_fu_672_p3;
wire   [0:0] icmp_ln1494_19_fu_684_p2;
wire   [14:0] trunc_ln45_19_fu_690_p1;
wire   [14:0] select_ln45_19_fu_694_p3;
wire   [0:0] icmp_ln1494_20_fu_706_p2;
wire   [14:0] trunc_ln45_20_fu_712_p1;
wire   [14:0] select_ln45_20_fu_716_p3;
wire   [0:0] icmp_ln1494_21_fu_728_p2;
wire   [14:0] trunc_ln45_21_fu_734_p1;
wire   [14:0] select_ln45_21_fu_738_p3;
wire   [0:0] icmp_ln1494_22_fu_750_p2;
wire   [14:0] trunc_ln45_22_fu_756_p1;
wire   [14:0] select_ln45_22_fu_760_p3;
wire   [0:0] icmp_ln1494_23_fu_772_p2;
wire   [14:0] trunc_ln45_23_fu_778_p1;
wire   [14:0] select_ln45_23_fu_782_p3;
wire   [0:0] icmp_ln1494_24_fu_794_p2;
wire   [14:0] trunc_ln45_24_fu_800_p1;
wire   [14:0] select_ln45_24_fu_804_p3;
wire   [0:0] icmp_ln1494_25_fu_816_p2;
wire   [14:0] trunc_ln45_25_fu_822_p1;
wire   [14:0] select_ln45_25_fu_826_p3;
wire   [0:0] icmp_ln1494_26_fu_838_p2;
wire   [14:0] trunc_ln45_26_fu_844_p1;
wire   [14:0] select_ln45_26_fu_848_p3;
wire   [0:0] icmp_ln1494_27_fu_860_p2;
wire   [14:0] trunc_ln45_27_fu_866_p1;
wire   [14:0] select_ln45_27_fu_870_p3;
wire   [0:0] icmp_ln1494_28_fu_882_p2;
wire   [14:0] trunc_ln45_28_fu_888_p1;
wire   [14:0] select_ln45_28_fu_892_p3;
wire   [0:0] icmp_ln1494_29_fu_904_p2;
wire   [14:0] trunc_ln45_29_fu_910_p1;
wire   [14:0] select_ln45_29_fu_914_p3;
wire   [0:0] icmp_ln1494_30_fu_926_p2;
wire   [14:0] trunc_ln45_30_fu_932_p1;
wire   [14:0] select_ln45_30_fu_936_p3;
wire   [15:0] zext_ln45_fu_284_p1;
wire   [15:0] zext_ln45_1_fu_306_p1;
wire   [15:0] zext_ln45_2_fu_328_p1;
wire   [15:0] zext_ln45_3_fu_350_p1;
wire   [15:0] zext_ln45_4_fu_372_p1;
wire   [15:0] zext_ln45_5_fu_394_p1;
wire   [15:0] zext_ln45_6_fu_416_p1;
wire   [15:0] zext_ln45_7_fu_438_p1;
wire   [15:0] zext_ln45_8_fu_460_p1;
wire   [15:0] zext_ln45_9_fu_482_p1;
wire   [15:0] zext_ln45_10_fu_504_p1;
wire   [15:0] zext_ln45_11_fu_526_p1;
wire   [15:0] zext_ln45_12_fu_548_p1;
wire   [15:0] zext_ln45_13_fu_570_p1;
wire   [15:0] zext_ln45_14_fu_592_p1;
wire   [15:0] zext_ln45_15_fu_614_p1;
wire   [15:0] zext_ln45_16_fu_636_p1;
wire   [15:0] zext_ln45_17_fu_658_p1;
wire   [15:0] zext_ln45_18_fu_680_p1;
wire   [15:0] zext_ln45_19_fu_702_p1;
wire   [15:0] zext_ln45_20_fu_724_p1;
wire   [15:0] zext_ln45_21_fu_746_p1;
wire   [15:0] zext_ln45_22_fu_768_p1;
wire   [15:0] zext_ln45_23_fu_790_p1;
wire   [15:0] zext_ln45_24_fu_812_p1;
wire   [15:0] zext_ln45_25_fu_834_p1;
wire   [15:0] zext_ln45_26_fu_856_p1;
wire   [15:0] zext_ln45_27_fu_878_p1;
wire   [15:0] zext_ln45_28_fu_900_p1;
wire   [15:0] zext_ln45_29_fu_922_p1;
wire   [15:0] zext_ln45_30_fu_944_p1;

assign ap_ready = 1'b1;

assign ap_return_0 = zext_ln45_fu_284_p1;

assign ap_return_1 = zext_ln45_1_fu_306_p1;

assign ap_return_10 = zext_ln45_10_fu_504_p1;

assign ap_return_11 = zext_ln45_11_fu_526_p1;

assign ap_return_12 = zext_ln45_12_fu_548_p1;

assign ap_return_13 = zext_ln45_13_fu_570_p1;

assign ap_return_14 = zext_ln45_14_fu_592_p1;

assign ap_return_15 = zext_ln45_15_fu_614_p1;

assign ap_return_16 = zext_ln45_16_fu_636_p1;

assign ap_return_17 = zext_ln45_17_fu_658_p1;

assign ap_return_18 = zext_ln45_18_fu_680_p1;

assign ap_return_19 = zext_ln45_19_fu_702_p1;

assign ap_return_2 = zext_ln45_2_fu_328_p1;

assign ap_return_20 = zext_ln45_20_fu_724_p1;

assign ap_return_21 = zext_ln45_21_fu_746_p1;

assign ap_return_22 = zext_ln45_22_fu_768_p1;

assign ap_return_23 = zext_ln45_23_fu_790_p1;

assign ap_return_24 = zext_ln45_24_fu_812_p1;

assign ap_return_25 = zext_ln45_25_fu_834_p1;

assign ap_return_26 = zext_ln45_26_fu_856_p1;

assign ap_return_27 = zext_ln45_27_fu_878_p1;

assign ap_return_28 = zext_ln45_28_fu_900_p1;

assign ap_return_29 = zext_ln45_29_fu_922_p1;

assign ap_return_3 = zext_ln45_3_fu_350_p1;

assign ap_return_30 = zext_ln45_30_fu_944_p1;

assign ap_return_4 = zext_ln45_4_fu_372_p1;

assign ap_return_5 = zext_ln45_5_fu_394_p1;

assign ap_return_6 = zext_ln45_6_fu_416_p1;

assign ap_return_7 = zext_ln45_7_fu_438_p1;

assign ap_return_8 = zext_ln45_8_fu_460_p1;

assign ap_return_9 = zext_ln45_9_fu_482_p1;

assign icmp_ln1494_10_fu_486_p2 = (($signed(data_10_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_508_p2 = (($signed(data_11_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_530_p2 = (($signed(data_12_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_552_p2 = (($signed(data_13_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_574_p2 = (($signed(data_15_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_596_p2 = (($signed(data_16_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_618_p2 = (($signed(data_17_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_640_p2 = (($signed(data_18_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_662_p2 = (($signed(data_19_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_684_p2 = (($signed(data_20_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_288_p2 = (($signed(data_1_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_706_p2 = (($signed(data_21_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_21_fu_728_p2 = (($signed(data_22_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_22_fu_750_p2 = (($signed(data_23_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_23_fu_772_p2 = (($signed(data_24_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_24_fu_794_p2 = (($signed(data_25_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_25_fu_816_p2 = (($signed(data_26_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_26_fu_838_p2 = (($signed(data_27_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_27_fu_860_p2 = (($signed(data_28_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_28_fu_882_p2 = (($signed(data_29_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_29_fu_904_p2 = (($signed(data_30_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_310_p2 = (($signed(data_2_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_30_fu_926_p2 = (($signed(data_31_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_332_p2 = (($signed(data_3_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_354_p2 = (($signed(data_4_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_376_p2 = (($signed(data_5_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_398_p2 = (($signed(data_6_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_420_p2 = (($signed(data_7_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_442_p2 = (($signed(data_8_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_464_p2 = (($signed(data_9_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_266_p2 = (($signed(data_0_V_read) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign select_ln45_10_fu_496_p3 = ((icmp_ln1494_10_fu_486_p2[0:0] === 1'b1) ? trunc_ln45_10_fu_492_p1 : 15'd0);

assign select_ln45_11_fu_518_p3 = ((icmp_ln1494_11_fu_508_p2[0:0] === 1'b1) ? trunc_ln45_11_fu_514_p1 : 15'd0);

assign select_ln45_12_fu_540_p3 = ((icmp_ln1494_12_fu_530_p2[0:0] === 1'b1) ? trunc_ln45_12_fu_536_p1 : 15'd0);

assign select_ln45_13_fu_562_p3 = ((icmp_ln1494_13_fu_552_p2[0:0] === 1'b1) ? trunc_ln45_13_fu_558_p1 : 15'd0);

assign select_ln45_14_fu_584_p3 = ((icmp_ln1494_14_fu_574_p2[0:0] === 1'b1) ? trunc_ln45_14_fu_580_p1 : 15'd0);

assign select_ln45_15_fu_606_p3 = ((icmp_ln1494_15_fu_596_p2[0:0] === 1'b1) ? trunc_ln45_15_fu_602_p1 : 15'd0);

assign select_ln45_16_fu_628_p3 = ((icmp_ln1494_16_fu_618_p2[0:0] === 1'b1) ? trunc_ln45_16_fu_624_p1 : 15'd0);

assign select_ln45_17_fu_650_p3 = ((icmp_ln1494_17_fu_640_p2[0:0] === 1'b1) ? trunc_ln45_17_fu_646_p1 : 15'd0);

assign select_ln45_18_fu_672_p3 = ((icmp_ln1494_18_fu_662_p2[0:0] === 1'b1) ? trunc_ln45_18_fu_668_p1 : 15'd0);

assign select_ln45_19_fu_694_p3 = ((icmp_ln1494_19_fu_684_p2[0:0] === 1'b1) ? trunc_ln45_19_fu_690_p1 : 15'd0);

assign select_ln45_1_fu_298_p3 = ((icmp_ln1494_1_fu_288_p2[0:0] === 1'b1) ? trunc_ln45_1_fu_294_p1 : 15'd0);

assign select_ln45_20_fu_716_p3 = ((icmp_ln1494_20_fu_706_p2[0:0] === 1'b1) ? trunc_ln45_20_fu_712_p1 : 15'd0);

assign select_ln45_21_fu_738_p3 = ((icmp_ln1494_21_fu_728_p2[0:0] === 1'b1) ? trunc_ln45_21_fu_734_p1 : 15'd0);

assign select_ln45_22_fu_760_p3 = ((icmp_ln1494_22_fu_750_p2[0:0] === 1'b1) ? trunc_ln45_22_fu_756_p1 : 15'd0);

assign select_ln45_23_fu_782_p3 = ((icmp_ln1494_23_fu_772_p2[0:0] === 1'b1) ? trunc_ln45_23_fu_778_p1 : 15'd0);

assign select_ln45_24_fu_804_p3 = ((icmp_ln1494_24_fu_794_p2[0:0] === 1'b1) ? trunc_ln45_24_fu_800_p1 : 15'd0);

assign select_ln45_25_fu_826_p3 = ((icmp_ln1494_25_fu_816_p2[0:0] === 1'b1) ? trunc_ln45_25_fu_822_p1 : 15'd0);

assign select_ln45_26_fu_848_p3 = ((icmp_ln1494_26_fu_838_p2[0:0] === 1'b1) ? trunc_ln45_26_fu_844_p1 : 15'd0);

assign select_ln45_27_fu_870_p3 = ((icmp_ln1494_27_fu_860_p2[0:0] === 1'b1) ? trunc_ln45_27_fu_866_p1 : 15'd0);

assign select_ln45_28_fu_892_p3 = ((icmp_ln1494_28_fu_882_p2[0:0] === 1'b1) ? trunc_ln45_28_fu_888_p1 : 15'd0);

assign select_ln45_29_fu_914_p3 = ((icmp_ln1494_29_fu_904_p2[0:0] === 1'b1) ? trunc_ln45_29_fu_910_p1 : 15'd0);

assign select_ln45_2_fu_320_p3 = ((icmp_ln1494_2_fu_310_p2[0:0] === 1'b1) ? trunc_ln45_2_fu_316_p1 : 15'd0);

assign select_ln45_30_fu_936_p3 = ((icmp_ln1494_30_fu_926_p2[0:0] === 1'b1) ? trunc_ln45_30_fu_932_p1 : 15'd0);

assign select_ln45_3_fu_342_p3 = ((icmp_ln1494_3_fu_332_p2[0:0] === 1'b1) ? trunc_ln45_3_fu_338_p1 : 15'd0);

assign select_ln45_4_fu_364_p3 = ((icmp_ln1494_4_fu_354_p2[0:0] === 1'b1) ? trunc_ln45_4_fu_360_p1 : 15'd0);

assign select_ln45_5_fu_386_p3 = ((icmp_ln1494_5_fu_376_p2[0:0] === 1'b1) ? trunc_ln45_5_fu_382_p1 : 15'd0);

assign select_ln45_6_fu_408_p3 = ((icmp_ln1494_6_fu_398_p2[0:0] === 1'b1) ? trunc_ln45_6_fu_404_p1 : 15'd0);

assign select_ln45_7_fu_430_p3 = ((icmp_ln1494_7_fu_420_p2[0:0] === 1'b1) ? trunc_ln45_7_fu_426_p1 : 15'd0);

assign select_ln45_8_fu_452_p3 = ((icmp_ln1494_8_fu_442_p2[0:0] === 1'b1) ? trunc_ln45_8_fu_448_p1 : 15'd0);

assign select_ln45_9_fu_474_p3 = ((icmp_ln1494_9_fu_464_p2[0:0] === 1'b1) ? trunc_ln45_9_fu_470_p1 : 15'd0);

assign select_ln45_fu_276_p3 = ((icmp_ln1494_fu_266_p2[0:0] === 1'b1) ? trunc_ln45_fu_272_p1 : 15'd0);

assign trunc_ln45_10_fu_492_p1 = data_10_V_read[14:0];

assign trunc_ln45_11_fu_514_p1 = data_11_V_read[14:0];

assign trunc_ln45_12_fu_536_p1 = data_12_V_read[14:0];

assign trunc_ln45_13_fu_558_p1 = data_13_V_read[14:0];

assign trunc_ln45_14_fu_580_p1 = data_15_V_read[14:0];

assign trunc_ln45_15_fu_602_p1 = data_16_V_read[14:0];

assign trunc_ln45_16_fu_624_p1 = data_17_V_read[14:0];

assign trunc_ln45_17_fu_646_p1 = data_18_V_read[14:0];

assign trunc_ln45_18_fu_668_p1 = data_19_V_read[14:0];

assign trunc_ln45_19_fu_690_p1 = data_20_V_read[14:0];

assign trunc_ln45_1_fu_294_p1 = data_1_V_read[14:0];

assign trunc_ln45_20_fu_712_p1 = data_21_V_read[14:0];

assign trunc_ln45_21_fu_734_p1 = data_22_V_read[14:0];

assign trunc_ln45_22_fu_756_p1 = data_23_V_read[14:0];

assign trunc_ln45_23_fu_778_p1 = data_24_V_read[14:0];

assign trunc_ln45_24_fu_800_p1 = data_25_V_read[14:0];

assign trunc_ln45_25_fu_822_p1 = data_26_V_read[14:0];

assign trunc_ln45_26_fu_844_p1 = data_27_V_read[14:0];

assign trunc_ln45_27_fu_866_p1 = data_28_V_read[14:0];

assign trunc_ln45_28_fu_888_p1 = data_29_V_read[14:0];

assign trunc_ln45_29_fu_910_p1 = data_30_V_read[14:0];

assign trunc_ln45_2_fu_316_p1 = data_2_V_read[14:0];

assign trunc_ln45_30_fu_932_p1 = data_31_V_read[14:0];

assign trunc_ln45_3_fu_338_p1 = data_3_V_read[14:0];

assign trunc_ln45_4_fu_360_p1 = data_4_V_read[14:0];

assign trunc_ln45_5_fu_382_p1 = data_5_V_read[14:0];

assign trunc_ln45_6_fu_404_p1 = data_6_V_read[14:0];

assign trunc_ln45_7_fu_426_p1 = data_7_V_read[14:0];

assign trunc_ln45_8_fu_448_p1 = data_8_V_read[14:0];

assign trunc_ln45_9_fu_470_p1 = data_9_V_read[14:0];

assign trunc_ln45_fu_272_p1 = data_0_V_read[14:0];

assign zext_ln45_10_fu_504_p1 = select_ln45_10_fu_496_p3;

assign zext_ln45_11_fu_526_p1 = select_ln45_11_fu_518_p3;

assign zext_ln45_12_fu_548_p1 = select_ln45_12_fu_540_p3;

assign zext_ln45_13_fu_570_p1 = select_ln45_13_fu_562_p3;

assign zext_ln45_14_fu_592_p1 = select_ln45_14_fu_584_p3;

assign zext_ln45_15_fu_614_p1 = select_ln45_15_fu_606_p3;

assign zext_ln45_16_fu_636_p1 = select_ln45_16_fu_628_p3;

assign zext_ln45_17_fu_658_p1 = select_ln45_17_fu_650_p3;

assign zext_ln45_18_fu_680_p1 = select_ln45_18_fu_672_p3;

assign zext_ln45_19_fu_702_p1 = select_ln45_19_fu_694_p3;

assign zext_ln45_1_fu_306_p1 = select_ln45_1_fu_298_p3;

assign zext_ln45_20_fu_724_p1 = select_ln45_20_fu_716_p3;

assign zext_ln45_21_fu_746_p1 = select_ln45_21_fu_738_p3;

assign zext_ln45_22_fu_768_p1 = select_ln45_22_fu_760_p3;

assign zext_ln45_23_fu_790_p1 = select_ln45_23_fu_782_p3;

assign zext_ln45_24_fu_812_p1 = select_ln45_24_fu_804_p3;

assign zext_ln45_25_fu_834_p1 = select_ln45_25_fu_826_p3;

assign zext_ln45_26_fu_856_p1 = select_ln45_26_fu_848_p3;

assign zext_ln45_27_fu_878_p1 = select_ln45_27_fu_870_p3;

assign zext_ln45_28_fu_900_p1 = select_ln45_28_fu_892_p3;

assign zext_ln45_29_fu_922_p1 = select_ln45_29_fu_914_p3;

assign zext_ln45_2_fu_328_p1 = select_ln45_2_fu_320_p3;

assign zext_ln45_30_fu_944_p1 = select_ln45_30_fu_936_p3;

assign zext_ln45_3_fu_350_p1 = select_ln45_3_fu_342_p3;

assign zext_ln45_4_fu_372_p1 = select_ln45_4_fu_364_p3;

assign zext_ln45_5_fu_394_p1 = select_ln45_5_fu_386_p3;

assign zext_ln45_6_fu_416_p1 = select_ln45_6_fu_408_p3;

assign zext_ln45_7_fu_438_p1 = select_ln45_7_fu_430_p3;

assign zext_ln45_8_fu_460_p1 = select_ln45_8_fu_452_p3;

assign zext_ln45_9_fu_482_p1 = select_ln45_9_fu_474_p3;

assign zext_ln45_fu_284_p1 = select_ln45_fu_276_p3;

endmodule //relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s
