// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::ap_const_logic_1 = sc_dt::Log_1;
const bool relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::ap_const_boolean_1 = true;
const sc_lv<16> relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<15> relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::ap_const_lv15_0 = "000000000000000";
const sc_logic relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::ap_const_logic_0 = sc_dt::Log_0;

relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( zext_ln45_fu_292_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( zext_ln45_1_fu_314_p1 );

    SC_METHOD(thread_ap_return_10);
    sensitive << ( zext_ln45_10_fu_512_p1 );

    SC_METHOD(thread_ap_return_11);
    sensitive << ( zext_ln45_11_fu_534_p1 );

    SC_METHOD(thread_ap_return_12);
    sensitive << ( zext_ln45_12_fu_556_p1 );

    SC_METHOD(thread_ap_return_13);
    sensitive << ( zext_ln45_13_fu_578_p1 );

    SC_METHOD(thread_ap_return_14);
    sensitive << ( zext_ln45_14_fu_600_p1 );

    SC_METHOD(thread_ap_return_15);
    sensitive << ( zext_ln45_15_fu_622_p1 );

    SC_METHOD(thread_ap_return_16);
    sensitive << ( zext_ln45_16_fu_644_p1 );

    SC_METHOD(thread_ap_return_17);
    sensitive << ( zext_ln45_17_fu_666_p1 );

    SC_METHOD(thread_ap_return_18);
    sensitive << ( zext_ln45_18_fu_688_p1 );

    SC_METHOD(thread_ap_return_19);
    sensitive << ( zext_ln45_19_fu_710_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( zext_ln45_2_fu_336_p1 );

    SC_METHOD(thread_ap_return_20);
    sensitive << ( zext_ln45_20_fu_732_p1 );

    SC_METHOD(thread_ap_return_21);
    sensitive << ( zext_ln45_21_fu_754_p1 );

    SC_METHOD(thread_ap_return_22);
    sensitive << ( zext_ln45_22_fu_776_p1 );

    SC_METHOD(thread_ap_return_23);
    sensitive << ( zext_ln45_23_fu_798_p1 );

    SC_METHOD(thread_ap_return_24);
    sensitive << ( zext_ln45_24_fu_820_p1 );

    SC_METHOD(thread_ap_return_25);
    sensitive << ( zext_ln45_25_fu_842_p1 );

    SC_METHOD(thread_ap_return_26);
    sensitive << ( zext_ln45_26_fu_864_p1 );

    SC_METHOD(thread_ap_return_27);
    sensitive << ( zext_ln45_27_fu_886_p1 );

    SC_METHOD(thread_ap_return_28);
    sensitive << ( zext_ln45_28_fu_908_p1 );

    SC_METHOD(thread_ap_return_29);
    sensitive << ( zext_ln45_29_fu_930_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( zext_ln45_3_fu_358_p1 );

    SC_METHOD(thread_ap_return_30);
    sensitive << ( zext_ln45_30_fu_952_p1 );

    SC_METHOD(thread_ap_return_31);
    sensitive << ( zext_ln45_31_fu_974_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( zext_ln45_4_fu_380_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( zext_ln45_5_fu_402_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( zext_ln45_6_fu_424_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( zext_ln45_7_fu_446_p1 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( zext_ln45_8_fu_468_p1 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( zext_ln45_9_fu_490_p1 );

    SC_METHOD(thread_icmp_ln1494_10_fu_494_p2);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_icmp_ln1494_11_fu_516_p2);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_icmp_ln1494_12_fu_538_p2);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_icmp_ln1494_13_fu_560_p2);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_icmp_ln1494_14_fu_582_p2);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_icmp_ln1494_15_fu_604_p2);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_icmp_ln1494_16_fu_626_p2);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_icmp_ln1494_17_fu_648_p2);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_icmp_ln1494_18_fu_670_p2);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_icmp_ln1494_19_fu_692_p2);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_icmp_ln1494_1_fu_296_p2);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1494_20_fu_714_p2);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_icmp_ln1494_21_fu_736_p2);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_icmp_ln1494_22_fu_758_p2);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_icmp_ln1494_23_fu_780_p2);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_icmp_ln1494_24_fu_802_p2);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_icmp_ln1494_25_fu_824_p2);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_icmp_ln1494_26_fu_846_p2);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_icmp_ln1494_27_fu_868_p2);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_icmp_ln1494_28_fu_890_p2);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_icmp_ln1494_29_fu_912_p2);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_icmp_ln1494_2_fu_318_p2);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1494_30_fu_934_p2);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_icmp_ln1494_31_fu_956_p2);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_icmp_ln1494_3_fu_340_p2);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1494_4_fu_362_p2);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1494_5_fu_384_p2);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_icmp_ln1494_6_fu_406_p2);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_icmp_ln1494_7_fu_428_p2);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_icmp_ln1494_8_fu_450_p2);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_icmp_ln1494_9_fu_472_p2);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_icmp_ln1494_fu_274_p2);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_select_ln45_10_fu_504_p3);
    sensitive << ( icmp_ln1494_10_fu_494_p2 );
    sensitive << ( trunc_ln45_10_fu_500_p1 );

    SC_METHOD(thread_select_ln45_11_fu_526_p3);
    sensitive << ( icmp_ln1494_11_fu_516_p2 );
    sensitive << ( trunc_ln45_11_fu_522_p1 );

    SC_METHOD(thread_select_ln45_12_fu_548_p3);
    sensitive << ( icmp_ln1494_12_fu_538_p2 );
    sensitive << ( trunc_ln45_12_fu_544_p1 );

    SC_METHOD(thread_select_ln45_13_fu_570_p3);
    sensitive << ( icmp_ln1494_13_fu_560_p2 );
    sensitive << ( trunc_ln45_13_fu_566_p1 );

    SC_METHOD(thread_select_ln45_14_fu_592_p3);
    sensitive << ( icmp_ln1494_14_fu_582_p2 );
    sensitive << ( trunc_ln45_14_fu_588_p1 );

    SC_METHOD(thread_select_ln45_15_fu_614_p3);
    sensitive << ( icmp_ln1494_15_fu_604_p2 );
    sensitive << ( trunc_ln45_15_fu_610_p1 );

    SC_METHOD(thread_select_ln45_16_fu_636_p3);
    sensitive << ( icmp_ln1494_16_fu_626_p2 );
    sensitive << ( trunc_ln45_16_fu_632_p1 );

    SC_METHOD(thread_select_ln45_17_fu_658_p3);
    sensitive << ( icmp_ln1494_17_fu_648_p2 );
    sensitive << ( trunc_ln45_17_fu_654_p1 );

    SC_METHOD(thread_select_ln45_18_fu_680_p3);
    sensitive << ( icmp_ln1494_18_fu_670_p2 );
    sensitive << ( trunc_ln45_18_fu_676_p1 );

    SC_METHOD(thread_select_ln45_19_fu_702_p3);
    sensitive << ( icmp_ln1494_19_fu_692_p2 );
    sensitive << ( trunc_ln45_19_fu_698_p1 );

    SC_METHOD(thread_select_ln45_1_fu_306_p3);
    sensitive << ( icmp_ln1494_1_fu_296_p2 );
    sensitive << ( trunc_ln45_1_fu_302_p1 );

    SC_METHOD(thread_select_ln45_20_fu_724_p3);
    sensitive << ( icmp_ln1494_20_fu_714_p2 );
    sensitive << ( trunc_ln45_20_fu_720_p1 );

    SC_METHOD(thread_select_ln45_21_fu_746_p3);
    sensitive << ( icmp_ln1494_21_fu_736_p2 );
    sensitive << ( trunc_ln45_21_fu_742_p1 );

    SC_METHOD(thread_select_ln45_22_fu_768_p3);
    sensitive << ( icmp_ln1494_22_fu_758_p2 );
    sensitive << ( trunc_ln45_22_fu_764_p1 );

    SC_METHOD(thread_select_ln45_23_fu_790_p3);
    sensitive << ( icmp_ln1494_23_fu_780_p2 );
    sensitive << ( trunc_ln45_23_fu_786_p1 );

    SC_METHOD(thread_select_ln45_24_fu_812_p3);
    sensitive << ( icmp_ln1494_24_fu_802_p2 );
    sensitive << ( trunc_ln45_24_fu_808_p1 );

    SC_METHOD(thread_select_ln45_25_fu_834_p3);
    sensitive << ( icmp_ln1494_25_fu_824_p2 );
    sensitive << ( trunc_ln45_25_fu_830_p1 );

    SC_METHOD(thread_select_ln45_26_fu_856_p3);
    sensitive << ( icmp_ln1494_26_fu_846_p2 );
    sensitive << ( trunc_ln45_26_fu_852_p1 );

    SC_METHOD(thread_select_ln45_27_fu_878_p3);
    sensitive << ( icmp_ln1494_27_fu_868_p2 );
    sensitive << ( trunc_ln45_27_fu_874_p1 );

    SC_METHOD(thread_select_ln45_28_fu_900_p3);
    sensitive << ( icmp_ln1494_28_fu_890_p2 );
    sensitive << ( trunc_ln45_28_fu_896_p1 );

    SC_METHOD(thread_select_ln45_29_fu_922_p3);
    sensitive << ( icmp_ln1494_29_fu_912_p2 );
    sensitive << ( trunc_ln45_29_fu_918_p1 );

    SC_METHOD(thread_select_ln45_2_fu_328_p3);
    sensitive << ( icmp_ln1494_2_fu_318_p2 );
    sensitive << ( trunc_ln45_2_fu_324_p1 );

    SC_METHOD(thread_select_ln45_30_fu_944_p3);
    sensitive << ( icmp_ln1494_30_fu_934_p2 );
    sensitive << ( trunc_ln45_30_fu_940_p1 );

    SC_METHOD(thread_select_ln45_31_fu_966_p3);
    sensitive << ( icmp_ln1494_31_fu_956_p2 );
    sensitive << ( trunc_ln45_31_fu_962_p1 );

    SC_METHOD(thread_select_ln45_3_fu_350_p3);
    sensitive << ( icmp_ln1494_3_fu_340_p2 );
    sensitive << ( trunc_ln45_3_fu_346_p1 );

    SC_METHOD(thread_select_ln45_4_fu_372_p3);
    sensitive << ( icmp_ln1494_4_fu_362_p2 );
    sensitive << ( trunc_ln45_4_fu_368_p1 );

    SC_METHOD(thread_select_ln45_5_fu_394_p3);
    sensitive << ( icmp_ln1494_5_fu_384_p2 );
    sensitive << ( trunc_ln45_5_fu_390_p1 );

    SC_METHOD(thread_select_ln45_6_fu_416_p3);
    sensitive << ( icmp_ln1494_6_fu_406_p2 );
    sensitive << ( trunc_ln45_6_fu_412_p1 );

    SC_METHOD(thread_select_ln45_7_fu_438_p3);
    sensitive << ( icmp_ln1494_7_fu_428_p2 );
    sensitive << ( trunc_ln45_7_fu_434_p1 );

    SC_METHOD(thread_select_ln45_8_fu_460_p3);
    sensitive << ( icmp_ln1494_8_fu_450_p2 );
    sensitive << ( trunc_ln45_8_fu_456_p1 );

    SC_METHOD(thread_select_ln45_9_fu_482_p3);
    sensitive << ( icmp_ln1494_9_fu_472_p2 );
    sensitive << ( trunc_ln45_9_fu_478_p1 );

    SC_METHOD(thread_select_ln45_fu_284_p3);
    sensitive << ( icmp_ln1494_fu_274_p2 );
    sensitive << ( trunc_ln45_fu_280_p1 );

    SC_METHOD(thread_trunc_ln45_10_fu_500_p1);
    sensitive << ( data_10_V_read );

    SC_METHOD(thread_trunc_ln45_11_fu_522_p1);
    sensitive << ( data_11_V_read );

    SC_METHOD(thread_trunc_ln45_12_fu_544_p1);
    sensitive << ( data_12_V_read );

    SC_METHOD(thread_trunc_ln45_13_fu_566_p1);
    sensitive << ( data_13_V_read );

    SC_METHOD(thread_trunc_ln45_14_fu_588_p1);
    sensitive << ( data_14_V_read );

    SC_METHOD(thread_trunc_ln45_15_fu_610_p1);
    sensitive << ( data_15_V_read );

    SC_METHOD(thread_trunc_ln45_16_fu_632_p1);
    sensitive << ( data_16_V_read );

    SC_METHOD(thread_trunc_ln45_17_fu_654_p1);
    sensitive << ( data_17_V_read );

    SC_METHOD(thread_trunc_ln45_18_fu_676_p1);
    sensitive << ( data_18_V_read );

    SC_METHOD(thread_trunc_ln45_19_fu_698_p1);
    sensitive << ( data_19_V_read );

    SC_METHOD(thread_trunc_ln45_1_fu_302_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_trunc_ln45_20_fu_720_p1);
    sensitive << ( data_20_V_read );

    SC_METHOD(thread_trunc_ln45_21_fu_742_p1);
    sensitive << ( data_21_V_read );

    SC_METHOD(thread_trunc_ln45_22_fu_764_p1);
    sensitive << ( data_22_V_read );

    SC_METHOD(thread_trunc_ln45_23_fu_786_p1);
    sensitive << ( data_23_V_read );

    SC_METHOD(thread_trunc_ln45_24_fu_808_p1);
    sensitive << ( data_24_V_read );

    SC_METHOD(thread_trunc_ln45_25_fu_830_p1);
    sensitive << ( data_25_V_read );

    SC_METHOD(thread_trunc_ln45_26_fu_852_p1);
    sensitive << ( data_26_V_read );

    SC_METHOD(thread_trunc_ln45_27_fu_874_p1);
    sensitive << ( data_27_V_read );

    SC_METHOD(thread_trunc_ln45_28_fu_896_p1);
    sensitive << ( data_28_V_read );

    SC_METHOD(thread_trunc_ln45_29_fu_918_p1);
    sensitive << ( data_29_V_read );

    SC_METHOD(thread_trunc_ln45_2_fu_324_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_trunc_ln45_30_fu_940_p1);
    sensitive << ( data_30_V_read );

    SC_METHOD(thread_trunc_ln45_31_fu_962_p1);
    sensitive << ( data_31_V_read );

    SC_METHOD(thread_trunc_ln45_3_fu_346_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_trunc_ln45_4_fu_368_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln45_5_fu_390_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_trunc_ln45_6_fu_412_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_trunc_ln45_7_fu_434_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln45_8_fu_456_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_trunc_ln45_9_fu_478_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_trunc_ln45_fu_280_p1);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_zext_ln45_10_fu_512_p1);
    sensitive << ( select_ln45_10_fu_504_p3 );

    SC_METHOD(thread_zext_ln45_11_fu_534_p1);
    sensitive << ( select_ln45_11_fu_526_p3 );

    SC_METHOD(thread_zext_ln45_12_fu_556_p1);
    sensitive << ( select_ln45_12_fu_548_p3 );

    SC_METHOD(thread_zext_ln45_13_fu_578_p1);
    sensitive << ( select_ln45_13_fu_570_p3 );

    SC_METHOD(thread_zext_ln45_14_fu_600_p1);
    sensitive << ( select_ln45_14_fu_592_p3 );

    SC_METHOD(thread_zext_ln45_15_fu_622_p1);
    sensitive << ( select_ln45_15_fu_614_p3 );

    SC_METHOD(thread_zext_ln45_16_fu_644_p1);
    sensitive << ( select_ln45_16_fu_636_p3 );

    SC_METHOD(thread_zext_ln45_17_fu_666_p1);
    sensitive << ( select_ln45_17_fu_658_p3 );

    SC_METHOD(thread_zext_ln45_18_fu_688_p1);
    sensitive << ( select_ln45_18_fu_680_p3 );

    SC_METHOD(thread_zext_ln45_19_fu_710_p1);
    sensitive << ( select_ln45_19_fu_702_p3 );

    SC_METHOD(thread_zext_ln45_1_fu_314_p1);
    sensitive << ( select_ln45_1_fu_306_p3 );

    SC_METHOD(thread_zext_ln45_20_fu_732_p1);
    sensitive << ( select_ln45_20_fu_724_p3 );

    SC_METHOD(thread_zext_ln45_21_fu_754_p1);
    sensitive << ( select_ln45_21_fu_746_p3 );

    SC_METHOD(thread_zext_ln45_22_fu_776_p1);
    sensitive << ( select_ln45_22_fu_768_p3 );

    SC_METHOD(thread_zext_ln45_23_fu_798_p1);
    sensitive << ( select_ln45_23_fu_790_p3 );

    SC_METHOD(thread_zext_ln45_24_fu_820_p1);
    sensitive << ( select_ln45_24_fu_812_p3 );

    SC_METHOD(thread_zext_ln45_25_fu_842_p1);
    sensitive << ( select_ln45_25_fu_834_p3 );

    SC_METHOD(thread_zext_ln45_26_fu_864_p1);
    sensitive << ( select_ln45_26_fu_856_p3 );

    SC_METHOD(thread_zext_ln45_27_fu_886_p1);
    sensitive << ( select_ln45_27_fu_878_p3 );

    SC_METHOD(thread_zext_ln45_28_fu_908_p1);
    sensitive << ( select_ln45_28_fu_900_p3 );

    SC_METHOD(thread_zext_ln45_29_fu_930_p1);
    sensitive << ( select_ln45_29_fu_922_p3 );

    SC_METHOD(thread_zext_ln45_2_fu_336_p1);
    sensitive << ( select_ln45_2_fu_328_p3 );

    SC_METHOD(thread_zext_ln45_30_fu_952_p1);
    sensitive << ( select_ln45_30_fu_944_p3 );

    SC_METHOD(thread_zext_ln45_31_fu_974_p1);
    sensitive << ( select_ln45_31_fu_966_p3 );

    SC_METHOD(thread_zext_ln45_3_fu_358_p1);
    sensitive << ( select_ln45_3_fu_350_p3 );

    SC_METHOD(thread_zext_ln45_4_fu_380_p1);
    sensitive << ( select_ln45_4_fu_372_p3 );

    SC_METHOD(thread_zext_ln45_5_fu_402_p1);
    sensitive << ( select_ln45_5_fu_394_p3 );

    SC_METHOD(thread_zext_ln45_6_fu_424_p1);
    sensitive << ( select_ln45_6_fu_416_p3 );

    SC_METHOD(thread_zext_ln45_7_fu_446_p1);
    sensitive << ( select_ln45_7_fu_438_p3 );

    SC_METHOD(thread_zext_ln45_8_fu_468_p1);
    sensitive << ( select_ln45_8_fu_460_p3 );

    SC_METHOD(thread_zext_ln45_9_fu_490_p1);
    sensitive << ( select_ln45_9_fu_482_p3 );

    SC_METHOD(thread_zext_ln45_fu_292_p1);
    sensitive << ( select_ln45_fu_284_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, data_10_V_read, "(port)data_10_V_read");
    sc_trace(mVcdFile, data_11_V_read, "(port)data_11_V_read");
    sc_trace(mVcdFile, data_12_V_read, "(port)data_12_V_read");
    sc_trace(mVcdFile, data_13_V_read, "(port)data_13_V_read");
    sc_trace(mVcdFile, data_14_V_read, "(port)data_14_V_read");
    sc_trace(mVcdFile, data_15_V_read, "(port)data_15_V_read");
    sc_trace(mVcdFile, data_16_V_read, "(port)data_16_V_read");
    sc_trace(mVcdFile, data_17_V_read, "(port)data_17_V_read");
    sc_trace(mVcdFile, data_18_V_read, "(port)data_18_V_read");
    sc_trace(mVcdFile, data_19_V_read, "(port)data_19_V_read");
    sc_trace(mVcdFile, data_20_V_read, "(port)data_20_V_read");
    sc_trace(mVcdFile, data_21_V_read, "(port)data_21_V_read");
    sc_trace(mVcdFile, data_22_V_read, "(port)data_22_V_read");
    sc_trace(mVcdFile, data_23_V_read, "(port)data_23_V_read");
    sc_trace(mVcdFile, data_24_V_read, "(port)data_24_V_read");
    sc_trace(mVcdFile, data_25_V_read, "(port)data_25_V_read");
    sc_trace(mVcdFile, data_26_V_read, "(port)data_26_V_read");
    sc_trace(mVcdFile, data_27_V_read, "(port)data_27_V_read");
    sc_trace(mVcdFile, data_28_V_read, "(port)data_28_V_read");
    sc_trace(mVcdFile, data_29_V_read, "(port)data_29_V_read");
    sc_trace(mVcdFile, data_30_V_read, "(port)data_30_V_read");
    sc_trace(mVcdFile, data_31_V_read, "(port)data_31_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, ap_return_10, "(port)ap_return_10");
    sc_trace(mVcdFile, ap_return_11, "(port)ap_return_11");
    sc_trace(mVcdFile, ap_return_12, "(port)ap_return_12");
    sc_trace(mVcdFile, ap_return_13, "(port)ap_return_13");
    sc_trace(mVcdFile, ap_return_14, "(port)ap_return_14");
    sc_trace(mVcdFile, ap_return_15, "(port)ap_return_15");
    sc_trace(mVcdFile, ap_return_16, "(port)ap_return_16");
    sc_trace(mVcdFile, ap_return_17, "(port)ap_return_17");
    sc_trace(mVcdFile, ap_return_18, "(port)ap_return_18");
    sc_trace(mVcdFile, ap_return_19, "(port)ap_return_19");
    sc_trace(mVcdFile, ap_return_20, "(port)ap_return_20");
    sc_trace(mVcdFile, ap_return_21, "(port)ap_return_21");
    sc_trace(mVcdFile, ap_return_22, "(port)ap_return_22");
    sc_trace(mVcdFile, ap_return_23, "(port)ap_return_23");
    sc_trace(mVcdFile, ap_return_24, "(port)ap_return_24");
    sc_trace(mVcdFile, ap_return_25, "(port)ap_return_25");
    sc_trace(mVcdFile, ap_return_26, "(port)ap_return_26");
    sc_trace(mVcdFile, ap_return_27, "(port)ap_return_27");
    sc_trace(mVcdFile, ap_return_28, "(port)ap_return_28");
    sc_trace(mVcdFile, ap_return_29, "(port)ap_return_29");
    sc_trace(mVcdFile, ap_return_30, "(port)ap_return_30");
    sc_trace(mVcdFile, ap_return_31, "(port)ap_return_31");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, icmp_ln1494_fu_274_p2, "icmp_ln1494_fu_274_p2");
    sc_trace(mVcdFile, trunc_ln45_fu_280_p1, "trunc_ln45_fu_280_p1");
    sc_trace(mVcdFile, select_ln45_fu_284_p3, "select_ln45_fu_284_p3");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_296_p2, "icmp_ln1494_1_fu_296_p2");
    sc_trace(mVcdFile, trunc_ln45_1_fu_302_p1, "trunc_ln45_1_fu_302_p1");
    sc_trace(mVcdFile, select_ln45_1_fu_306_p3, "select_ln45_1_fu_306_p3");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_318_p2, "icmp_ln1494_2_fu_318_p2");
    sc_trace(mVcdFile, trunc_ln45_2_fu_324_p1, "trunc_ln45_2_fu_324_p1");
    sc_trace(mVcdFile, select_ln45_2_fu_328_p3, "select_ln45_2_fu_328_p3");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_340_p2, "icmp_ln1494_3_fu_340_p2");
    sc_trace(mVcdFile, trunc_ln45_3_fu_346_p1, "trunc_ln45_3_fu_346_p1");
    sc_trace(mVcdFile, select_ln45_3_fu_350_p3, "select_ln45_3_fu_350_p3");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_362_p2, "icmp_ln1494_4_fu_362_p2");
    sc_trace(mVcdFile, trunc_ln45_4_fu_368_p1, "trunc_ln45_4_fu_368_p1");
    sc_trace(mVcdFile, select_ln45_4_fu_372_p3, "select_ln45_4_fu_372_p3");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_384_p2, "icmp_ln1494_5_fu_384_p2");
    sc_trace(mVcdFile, trunc_ln45_5_fu_390_p1, "trunc_ln45_5_fu_390_p1");
    sc_trace(mVcdFile, select_ln45_5_fu_394_p3, "select_ln45_5_fu_394_p3");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_406_p2, "icmp_ln1494_6_fu_406_p2");
    sc_trace(mVcdFile, trunc_ln45_6_fu_412_p1, "trunc_ln45_6_fu_412_p1");
    sc_trace(mVcdFile, select_ln45_6_fu_416_p3, "select_ln45_6_fu_416_p3");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_428_p2, "icmp_ln1494_7_fu_428_p2");
    sc_trace(mVcdFile, trunc_ln45_7_fu_434_p1, "trunc_ln45_7_fu_434_p1");
    sc_trace(mVcdFile, select_ln45_7_fu_438_p3, "select_ln45_7_fu_438_p3");
    sc_trace(mVcdFile, icmp_ln1494_8_fu_450_p2, "icmp_ln1494_8_fu_450_p2");
    sc_trace(mVcdFile, trunc_ln45_8_fu_456_p1, "trunc_ln45_8_fu_456_p1");
    sc_trace(mVcdFile, select_ln45_8_fu_460_p3, "select_ln45_8_fu_460_p3");
    sc_trace(mVcdFile, icmp_ln1494_9_fu_472_p2, "icmp_ln1494_9_fu_472_p2");
    sc_trace(mVcdFile, trunc_ln45_9_fu_478_p1, "trunc_ln45_9_fu_478_p1");
    sc_trace(mVcdFile, select_ln45_9_fu_482_p3, "select_ln45_9_fu_482_p3");
    sc_trace(mVcdFile, icmp_ln1494_10_fu_494_p2, "icmp_ln1494_10_fu_494_p2");
    sc_trace(mVcdFile, trunc_ln45_10_fu_500_p1, "trunc_ln45_10_fu_500_p1");
    sc_trace(mVcdFile, select_ln45_10_fu_504_p3, "select_ln45_10_fu_504_p3");
    sc_trace(mVcdFile, icmp_ln1494_11_fu_516_p2, "icmp_ln1494_11_fu_516_p2");
    sc_trace(mVcdFile, trunc_ln45_11_fu_522_p1, "trunc_ln45_11_fu_522_p1");
    sc_trace(mVcdFile, select_ln45_11_fu_526_p3, "select_ln45_11_fu_526_p3");
    sc_trace(mVcdFile, icmp_ln1494_12_fu_538_p2, "icmp_ln1494_12_fu_538_p2");
    sc_trace(mVcdFile, trunc_ln45_12_fu_544_p1, "trunc_ln45_12_fu_544_p1");
    sc_trace(mVcdFile, select_ln45_12_fu_548_p3, "select_ln45_12_fu_548_p3");
    sc_trace(mVcdFile, icmp_ln1494_13_fu_560_p2, "icmp_ln1494_13_fu_560_p2");
    sc_trace(mVcdFile, trunc_ln45_13_fu_566_p1, "trunc_ln45_13_fu_566_p1");
    sc_trace(mVcdFile, select_ln45_13_fu_570_p3, "select_ln45_13_fu_570_p3");
    sc_trace(mVcdFile, icmp_ln1494_14_fu_582_p2, "icmp_ln1494_14_fu_582_p2");
    sc_trace(mVcdFile, trunc_ln45_14_fu_588_p1, "trunc_ln45_14_fu_588_p1");
    sc_trace(mVcdFile, select_ln45_14_fu_592_p3, "select_ln45_14_fu_592_p3");
    sc_trace(mVcdFile, icmp_ln1494_15_fu_604_p2, "icmp_ln1494_15_fu_604_p2");
    sc_trace(mVcdFile, trunc_ln45_15_fu_610_p1, "trunc_ln45_15_fu_610_p1");
    sc_trace(mVcdFile, select_ln45_15_fu_614_p3, "select_ln45_15_fu_614_p3");
    sc_trace(mVcdFile, icmp_ln1494_16_fu_626_p2, "icmp_ln1494_16_fu_626_p2");
    sc_trace(mVcdFile, trunc_ln45_16_fu_632_p1, "trunc_ln45_16_fu_632_p1");
    sc_trace(mVcdFile, select_ln45_16_fu_636_p3, "select_ln45_16_fu_636_p3");
    sc_trace(mVcdFile, icmp_ln1494_17_fu_648_p2, "icmp_ln1494_17_fu_648_p2");
    sc_trace(mVcdFile, trunc_ln45_17_fu_654_p1, "trunc_ln45_17_fu_654_p1");
    sc_trace(mVcdFile, select_ln45_17_fu_658_p3, "select_ln45_17_fu_658_p3");
    sc_trace(mVcdFile, icmp_ln1494_18_fu_670_p2, "icmp_ln1494_18_fu_670_p2");
    sc_trace(mVcdFile, trunc_ln45_18_fu_676_p1, "trunc_ln45_18_fu_676_p1");
    sc_trace(mVcdFile, select_ln45_18_fu_680_p3, "select_ln45_18_fu_680_p3");
    sc_trace(mVcdFile, icmp_ln1494_19_fu_692_p2, "icmp_ln1494_19_fu_692_p2");
    sc_trace(mVcdFile, trunc_ln45_19_fu_698_p1, "trunc_ln45_19_fu_698_p1");
    sc_trace(mVcdFile, select_ln45_19_fu_702_p3, "select_ln45_19_fu_702_p3");
    sc_trace(mVcdFile, icmp_ln1494_20_fu_714_p2, "icmp_ln1494_20_fu_714_p2");
    sc_trace(mVcdFile, trunc_ln45_20_fu_720_p1, "trunc_ln45_20_fu_720_p1");
    sc_trace(mVcdFile, select_ln45_20_fu_724_p3, "select_ln45_20_fu_724_p3");
    sc_trace(mVcdFile, icmp_ln1494_21_fu_736_p2, "icmp_ln1494_21_fu_736_p2");
    sc_trace(mVcdFile, trunc_ln45_21_fu_742_p1, "trunc_ln45_21_fu_742_p1");
    sc_trace(mVcdFile, select_ln45_21_fu_746_p3, "select_ln45_21_fu_746_p3");
    sc_trace(mVcdFile, icmp_ln1494_22_fu_758_p2, "icmp_ln1494_22_fu_758_p2");
    sc_trace(mVcdFile, trunc_ln45_22_fu_764_p1, "trunc_ln45_22_fu_764_p1");
    sc_trace(mVcdFile, select_ln45_22_fu_768_p3, "select_ln45_22_fu_768_p3");
    sc_trace(mVcdFile, icmp_ln1494_23_fu_780_p2, "icmp_ln1494_23_fu_780_p2");
    sc_trace(mVcdFile, trunc_ln45_23_fu_786_p1, "trunc_ln45_23_fu_786_p1");
    sc_trace(mVcdFile, select_ln45_23_fu_790_p3, "select_ln45_23_fu_790_p3");
    sc_trace(mVcdFile, icmp_ln1494_24_fu_802_p2, "icmp_ln1494_24_fu_802_p2");
    sc_trace(mVcdFile, trunc_ln45_24_fu_808_p1, "trunc_ln45_24_fu_808_p1");
    sc_trace(mVcdFile, select_ln45_24_fu_812_p3, "select_ln45_24_fu_812_p3");
    sc_trace(mVcdFile, icmp_ln1494_25_fu_824_p2, "icmp_ln1494_25_fu_824_p2");
    sc_trace(mVcdFile, trunc_ln45_25_fu_830_p1, "trunc_ln45_25_fu_830_p1");
    sc_trace(mVcdFile, select_ln45_25_fu_834_p3, "select_ln45_25_fu_834_p3");
    sc_trace(mVcdFile, icmp_ln1494_26_fu_846_p2, "icmp_ln1494_26_fu_846_p2");
    sc_trace(mVcdFile, trunc_ln45_26_fu_852_p1, "trunc_ln45_26_fu_852_p1");
    sc_trace(mVcdFile, select_ln45_26_fu_856_p3, "select_ln45_26_fu_856_p3");
    sc_trace(mVcdFile, icmp_ln1494_27_fu_868_p2, "icmp_ln1494_27_fu_868_p2");
    sc_trace(mVcdFile, trunc_ln45_27_fu_874_p1, "trunc_ln45_27_fu_874_p1");
    sc_trace(mVcdFile, select_ln45_27_fu_878_p3, "select_ln45_27_fu_878_p3");
    sc_trace(mVcdFile, icmp_ln1494_28_fu_890_p2, "icmp_ln1494_28_fu_890_p2");
    sc_trace(mVcdFile, trunc_ln45_28_fu_896_p1, "trunc_ln45_28_fu_896_p1");
    sc_trace(mVcdFile, select_ln45_28_fu_900_p3, "select_ln45_28_fu_900_p3");
    sc_trace(mVcdFile, icmp_ln1494_29_fu_912_p2, "icmp_ln1494_29_fu_912_p2");
    sc_trace(mVcdFile, trunc_ln45_29_fu_918_p1, "trunc_ln45_29_fu_918_p1");
    sc_trace(mVcdFile, select_ln45_29_fu_922_p3, "select_ln45_29_fu_922_p3");
    sc_trace(mVcdFile, icmp_ln1494_30_fu_934_p2, "icmp_ln1494_30_fu_934_p2");
    sc_trace(mVcdFile, trunc_ln45_30_fu_940_p1, "trunc_ln45_30_fu_940_p1");
    sc_trace(mVcdFile, select_ln45_30_fu_944_p3, "select_ln45_30_fu_944_p3");
    sc_trace(mVcdFile, icmp_ln1494_31_fu_956_p2, "icmp_ln1494_31_fu_956_p2");
    sc_trace(mVcdFile, trunc_ln45_31_fu_962_p1, "trunc_ln45_31_fu_962_p1");
    sc_trace(mVcdFile, select_ln45_31_fu_966_p3, "select_ln45_31_fu_966_p3");
    sc_trace(mVcdFile, zext_ln45_fu_292_p1, "zext_ln45_fu_292_p1");
    sc_trace(mVcdFile, zext_ln45_1_fu_314_p1, "zext_ln45_1_fu_314_p1");
    sc_trace(mVcdFile, zext_ln45_2_fu_336_p1, "zext_ln45_2_fu_336_p1");
    sc_trace(mVcdFile, zext_ln45_3_fu_358_p1, "zext_ln45_3_fu_358_p1");
    sc_trace(mVcdFile, zext_ln45_4_fu_380_p1, "zext_ln45_4_fu_380_p1");
    sc_trace(mVcdFile, zext_ln45_5_fu_402_p1, "zext_ln45_5_fu_402_p1");
    sc_trace(mVcdFile, zext_ln45_6_fu_424_p1, "zext_ln45_6_fu_424_p1");
    sc_trace(mVcdFile, zext_ln45_7_fu_446_p1, "zext_ln45_7_fu_446_p1");
    sc_trace(mVcdFile, zext_ln45_8_fu_468_p1, "zext_ln45_8_fu_468_p1");
    sc_trace(mVcdFile, zext_ln45_9_fu_490_p1, "zext_ln45_9_fu_490_p1");
    sc_trace(mVcdFile, zext_ln45_10_fu_512_p1, "zext_ln45_10_fu_512_p1");
    sc_trace(mVcdFile, zext_ln45_11_fu_534_p1, "zext_ln45_11_fu_534_p1");
    sc_trace(mVcdFile, zext_ln45_12_fu_556_p1, "zext_ln45_12_fu_556_p1");
    sc_trace(mVcdFile, zext_ln45_13_fu_578_p1, "zext_ln45_13_fu_578_p1");
    sc_trace(mVcdFile, zext_ln45_14_fu_600_p1, "zext_ln45_14_fu_600_p1");
    sc_trace(mVcdFile, zext_ln45_15_fu_622_p1, "zext_ln45_15_fu_622_p1");
    sc_trace(mVcdFile, zext_ln45_16_fu_644_p1, "zext_ln45_16_fu_644_p1");
    sc_trace(mVcdFile, zext_ln45_17_fu_666_p1, "zext_ln45_17_fu_666_p1");
    sc_trace(mVcdFile, zext_ln45_18_fu_688_p1, "zext_ln45_18_fu_688_p1");
    sc_trace(mVcdFile, zext_ln45_19_fu_710_p1, "zext_ln45_19_fu_710_p1");
    sc_trace(mVcdFile, zext_ln45_20_fu_732_p1, "zext_ln45_20_fu_732_p1");
    sc_trace(mVcdFile, zext_ln45_21_fu_754_p1, "zext_ln45_21_fu_754_p1");
    sc_trace(mVcdFile, zext_ln45_22_fu_776_p1, "zext_ln45_22_fu_776_p1");
    sc_trace(mVcdFile, zext_ln45_23_fu_798_p1, "zext_ln45_23_fu_798_p1");
    sc_trace(mVcdFile, zext_ln45_24_fu_820_p1, "zext_ln45_24_fu_820_p1");
    sc_trace(mVcdFile, zext_ln45_25_fu_842_p1, "zext_ln45_25_fu_842_p1");
    sc_trace(mVcdFile, zext_ln45_26_fu_864_p1, "zext_ln45_26_fu_864_p1");
    sc_trace(mVcdFile, zext_ln45_27_fu_886_p1, "zext_ln45_27_fu_886_p1");
    sc_trace(mVcdFile, zext_ln45_28_fu_908_p1, "zext_ln45_28_fu_908_p1");
    sc_trace(mVcdFile, zext_ln45_29_fu_930_p1, "zext_ln45_29_fu_930_p1");
    sc_trace(mVcdFile, zext_ln45_30_fu_952_p1, "zext_ln45_30_fu_952_p1");
    sc_trace(mVcdFile, zext_ln45_31_fu_974_p1, "zext_ln45_31_fu_974_p1");
#endif

    }
}

relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::~relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_0() {
    ap_return_0 = zext_ln45_fu_292_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_1() {
    ap_return_1 = zext_ln45_1_fu_314_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_10() {
    ap_return_10 = zext_ln45_10_fu_512_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_11() {
    ap_return_11 = zext_ln45_11_fu_534_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_12() {
    ap_return_12 = zext_ln45_12_fu_556_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_13() {
    ap_return_13 = zext_ln45_13_fu_578_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_14() {
    ap_return_14 = zext_ln45_14_fu_600_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_15() {
    ap_return_15 = zext_ln45_15_fu_622_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_16() {
    ap_return_16 = zext_ln45_16_fu_644_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_17() {
    ap_return_17 = zext_ln45_17_fu_666_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_18() {
    ap_return_18 = zext_ln45_18_fu_688_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_19() {
    ap_return_19 = zext_ln45_19_fu_710_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_2() {
    ap_return_2 = zext_ln45_2_fu_336_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_20() {
    ap_return_20 = zext_ln45_20_fu_732_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_21() {
    ap_return_21 = zext_ln45_21_fu_754_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_22() {
    ap_return_22 = zext_ln45_22_fu_776_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_23() {
    ap_return_23 = zext_ln45_23_fu_798_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_24() {
    ap_return_24 = zext_ln45_24_fu_820_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_25() {
    ap_return_25 = zext_ln45_25_fu_842_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_26() {
    ap_return_26 = zext_ln45_26_fu_864_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_27() {
    ap_return_27 = zext_ln45_27_fu_886_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_28() {
    ap_return_28 = zext_ln45_28_fu_908_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_29() {
    ap_return_29 = zext_ln45_29_fu_930_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_3() {
    ap_return_3 = zext_ln45_3_fu_358_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_30() {
    ap_return_30 = zext_ln45_30_fu_952_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_31() {
    ap_return_31 = zext_ln45_31_fu_974_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_4() {
    ap_return_4 = zext_ln45_4_fu_380_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_5() {
    ap_return_5 = zext_ln45_5_fu_402_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_6() {
    ap_return_6 = zext_ln45_6_fu_424_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_7() {
    ap_return_7 = zext_ln45_7_fu_446_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_8() {
    ap_return_8 = zext_ln45_8_fu_468_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_ap_return_9() {
    ap_return_9 = zext_ln45_9_fu_490_p1.read();
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_10_fu_494_p2() {
    icmp_ln1494_10_fu_494_p2 = (!data_10_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_10_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_11_fu_516_p2() {
    icmp_ln1494_11_fu_516_p2 = (!data_11_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_11_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_12_fu_538_p2() {
    icmp_ln1494_12_fu_538_p2 = (!data_12_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_12_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_13_fu_560_p2() {
    icmp_ln1494_13_fu_560_p2 = (!data_13_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_13_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_14_fu_582_p2() {
    icmp_ln1494_14_fu_582_p2 = (!data_14_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_14_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_15_fu_604_p2() {
    icmp_ln1494_15_fu_604_p2 = (!data_15_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_15_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_16_fu_626_p2() {
    icmp_ln1494_16_fu_626_p2 = (!data_16_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_16_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_17_fu_648_p2() {
    icmp_ln1494_17_fu_648_p2 = (!data_17_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_17_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_18_fu_670_p2() {
    icmp_ln1494_18_fu_670_p2 = (!data_18_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_18_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_19_fu_692_p2() {
    icmp_ln1494_19_fu_692_p2 = (!data_19_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_19_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_1_fu_296_p2() {
    icmp_ln1494_1_fu_296_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_1_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_20_fu_714_p2() {
    icmp_ln1494_20_fu_714_p2 = (!data_20_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_20_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_21_fu_736_p2() {
    icmp_ln1494_21_fu_736_p2 = (!data_21_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_21_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_22_fu_758_p2() {
    icmp_ln1494_22_fu_758_p2 = (!data_22_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_22_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_23_fu_780_p2() {
    icmp_ln1494_23_fu_780_p2 = (!data_23_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_23_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_24_fu_802_p2() {
    icmp_ln1494_24_fu_802_p2 = (!data_24_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_24_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_25_fu_824_p2() {
    icmp_ln1494_25_fu_824_p2 = (!data_25_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_25_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_26_fu_846_p2() {
    icmp_ln1494_26_fu_846_p2 = (!data_26_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_26_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_27_fu_868_p2() {
    icmp_ln1494_27_fu_868_p2 = (!data_27_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_27_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_28_fu_890_p2() {
    icmp_ln1494_28_fu_890_p2 = (!data_28_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_28_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_29_fu_912_p2() {
    icmp_ln1494_29_fu_912_p2 = (!data_29_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_29_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_2_fu_318_p2() {
    icmp_ln1494_2_fu_318_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_2_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_30_fu_934_p2() {
    icmp_ln1494_30_fu_934_p2 = (!data_30_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_30_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_31_fu_956_p2() {
    icmp_ln1494_31_fu_956_p2 = (!data_31_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_31_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_3_fu_340_p2() {
    icmp_ln1494_3_fu_340_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_3_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_4_fu_362_p2() {
    icmp_ln1494_4_fu_362_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_4_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_5_fu_384_p2() {
    icmp_ln1494_5_fu_384_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_5_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_6_fu_406_p2() {
    icmp_ln1494_6_fu_406_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_6_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_7_fu_428_p2() {
    icmp_ln1494_7_fu_428_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_7_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_8_fu_450_p2() {
    icmp_ln1494_8_fu_450_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_8_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_9_fu_472_p2() {
    icmp_ln1494_9_fu_472_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_9_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_icmp_ln1494_fu_274_p2() {
    icmp_ln1494_fu_274_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_0_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_10_fu_504_p3() {
    select_ln45_10_fu_504_p3 = (!icmp_ln1494_10_fu_494_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_10_fu_494_p2.read()[0].to_bool())? trunc_ln45_10_fu_500_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_11_fu_526_p3() {
    select_ln45_11_fu_526_p3 = (!icmp_ln1494_11_fu_516_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_11_fu_516_p2.read()[0].to_bool())? trunc_ln45_11_fu_522_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_12_fu_548_p3() {
    select_ln45_12_fu_548_p3 = (!icmp_ln1494_12_fu_538_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_12_fu_538_p2.read()[0].to_bool())? trunc_ln45_12_fu_544_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_13_fu_570_p3() {
    select_ln45_13_fu_570_p3 = (!icmp_ln1494_13_fu_560_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_13_fu_560_p2.read()[0].to_bool())? trunc_ln45_13_fu_566_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_14_fu_592_p3() {
    select_ln45_14_fu_592_p3 = (!icmp_ln1494_14_fu_582_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_14_fu_582_p2.read()[0].to_bool())? trunc_ln45_14_fu_588_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_15_fu_614_p3() {
    select_ln45_15_fu_614_p3 = (!icmp_ln1494_15_fu_604_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_15_fu_604_p2.read()[0].to_bool())? trunc_ln45_15_fu_610_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_16_fu_636_p3() {
    select_ln45_16_fu_636_p3 = (!icmp_ln1494_16_fu_626_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_16_fu_626_p2.read()[0].to_bool())? trunc_ln45_16_fu_632_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_17_fu_658_p3() {
    select_ln45_17_fu_658_p3 = (!icmp_ln1494_17_fu_648_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_17_fu_648_p2.read()[0].to_bool())? trunc_ln45_17_fu_654_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_18_fu_680_p3() {
    select_ln45_18_fu_680_p3 = (!icmp_ln1494_18_fu_670_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_18_fu_670_p2.read()[0].to_bool())? trunc_ln45_18_fu_676_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_19_fu_702_p3() {
    select_ln45_19_fu_702_p3 = (!icmp_ln1494_19_fu_692_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_19_fu_692_p2.read()[0].to_bool())? trunc_ln45_19_fu_698_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_1_fu_306_p3() {
    select_ln45_1_fu_306_p3 = (!icmp_ln1494_1_fu_296_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_1_fu_296_p2.read()[0].to_bool())? trunc_ln45_1_fu_302_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_20_fu_724_p3() {
    select_ln45_20_fu_724_p3 = (!icmp_ln1494_20_fu_714_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_20_fu_714_p2.read()[0].to_bool())? trunc_ln45_20_fu_720_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_21_fu_746_p3() {
    select_ln45_21_fu_746_p3 = (!icmp_ln1494_21_fu_736_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_21_fu_736_p2.read()[0].to_bool())? trunc_ln45_21_fu_742_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_22_fu_768_p3() {
    select_ln45_22_fu_768_p3 = (!icmp_ln1494_22_fu_758_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_22_fu_758_p2.read()[0].to_bool())? trunc_ln45_22_fu_764_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_23_fu_790_p3() {
    select_ln45_23_fu_790_p3 = (!icmp_ln1494_23_fu_780_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_23_fu_780_p2.read()[0].to_bool())? trunc_ln45_23_fu_786_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_24_fu_812_p3() {
    select_ln45_24_fu_812_p3 = (!icmp_ln1494_24_fu_802_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_24_fu_802_p2.read()[0].to_bool())? trunc_ln45_24_fu_808_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_25_fu_834_p3() {
    select_ln45_25_fu_834_p3 = (!icmp_ln1494_25_fu_824_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_25_fu_824_p2.read()[0].to_bool())? trunc_ln45_25_fu_830_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_26_fu_856_p3() {
    select_ln45_26_fu_856_p3 = (!icmp_ln1494_26_fu_846_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_26_fu_846_p2.read()[0].to_bool())? trunc_ln45_26_fu_852_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_27_fu_878_p3() {
    select_ln45_27_fu_878_p3 = (!icmp_ln1494_27_fu_868_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_27_fu_868_p2.read()[0].to_bool())? trunc_ln45_27_fu_874_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_28_fu_900_p3() {
    select_ln45_28_fu_900_p3 = (!icmp_ln1494_28_fu_890_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_28_fu_890_p2.read()[0].to_bool())? trunc_ln45_28_fu_896_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_29_fu_922_p3() {
    select_ln45_29_fu_922_p3 = (!icmp_ln1494_29_fu_912_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_29_fu_912_p2.read()[0].to_bool())? trunc_ln45_29_fu_918_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_2_fu_328_p3() {
    select_ln45_2_fu_328_p3 = (!icmp_ln1494_2_fu_318_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_2_fu_318_p2.read()[0].to_bool())? trunc_ln45_2_fu_324_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_30_fu_944_p3() {
    select_ln45_30_fu_944_p3 = (!icmp_ln1494_30_fu_934_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_30_fu_934_p2.read()[0].to_bool())? trunc_ln45_30_fu_940_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_31_fu_966_p3() {
    select_ln45_31_fu_966_p3 = (!icmp_ln1494_31_fu_956_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_31_fu_956_p2.read()[0].to_bool())? trunc_ln45_31_fu_962_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_3_fu_350_p3() {
    select_ln45_3_fu_350_p3 = (!icmp_ln1494_3_fu_340_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_3_fu_340_p2.read()[0].to_bool())? trunc_ln45_3_fu_346_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_4_fu_372_p3() {
    select_ln45_4_fu_372_p3 = (!icmp_ln1494_4_fu_362_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_4_fu_362_p2.read()[0].to_bool())? trunc_ln45_4_fu_368_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_5_fu_394_p3() {
    select_ln45_5_fu_394_p3 = (!icmp_ln1494_5_fu_384_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_5_fu_384_p2.read()[0].to_bool())? trunc_ln45_5_fu_390_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_6_fu_416_p3() {
    select_ln45_6_fu_416_p3 = (!icmp_ln1494_6_fu_406_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_6_fu_406_p2.read()[0].to_bool())? trunc_ln45_6_fu_412_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_7_fu_438_p3() {
    select_ln45_7_fu_438_p3 = (!icmp_ln1494_7_fu_428_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_7_fu_428_p2.read()[0].to_bool())? trunc_ln45_7_fu_434_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_8_fu_460_p3() {
    select_ln45_8_fu_460_p3 = (!icmp_ln1494_8_fu_450_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_8_fu_450_p2.read()[0].to_bool())? trunc_ln45_8_fu_456_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_9_fu_482_p3() {
    select_ln45_9_fu_482_p3 = (!icmp_ln1494_9_fu_472_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_9_fu_472_p2.read()[0].to_bool())? trunc_ln45_9_fu_478_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_select_ln45_fu_284_p3() {
    select_ln45_fu_284_p3 = (!icmp_ln1494_fu_274_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_fu_274_p2.read()[0].to_bool())? trunc_ln45_fu_280_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_10_fu_500_p1() {
    trunc_ln45_10_fu_500_p1 = data_10_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_11_fu_522_p1() {
    trunc_ln45_11_fu_522_p1 = data_11_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_12_fu_544_p1() {
    trunc_ln45_12_fu_544_p1 = data_12_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_13_fu_566_p1() {
    trunc_ln45_13_fu_566_p1 = data_13_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_14_fu_588_p1() {
    trunc_ln45_14_fu_588_p1 = data_14_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_15_fu_610_p1() {
    trunc_ln45_15_fu_610_p1 = data_15_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_16_fu_632_p1() {
    trunc_ln45_16_fu_632_p1 = data_16_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_17_fu_654_p1() {
    trunc_ln45_17_fu_654_p1 = data_17_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_18_fu_676_p1() {
    trunc_ln45_18_fu_676_p1 = data_18_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_19_fu_698_p1() {
    trunc_ln45_19_fu_698_p1 = data_19_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_1_fu_302_p1() {
    trunc_ln45_1_fu_302_p1 = data_1_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_20_fu_720_p1() {
    trunc_ln45_20_fu_720_p1 = data_20_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_21_fu_742_p1() {
    trunc_ln45_21_fu_742_p1 = data_21_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_22_fu_764_p1() {
    trunc_ln45_22_fu_764_p1 = data_22_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_23_fu_786_p1() {
    trunc_ln45_23_fu_786_p1 = data_23_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_24_fu_808_p1() {
    trunc_ln45_24_fu_808_p1 = data_24_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_25_fu_830_p1() {
    trunc_ln45_25_fu_830_p1 = data_25_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_26_fu_852_p1() {
    trunc_ln45_26_fu_852_p1 = data_26_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_27_fu_874_p1() {
    trunc_ln45_27_fu_874_p1 = data_27_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_28_fu_896_p1() {
    trunc_ln45_28_fu_896_p1 = data_28_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_29_fu_918_p1() {
    trunc_ln45_29_fu_918_p1 = data_29_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_2_fu_324_p1() {
    trunc_ln45_2_fu_324_p1 = data_2_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_30_fu_940_p1() {
    trunc_ln45_30_fu_940_p1 = data_30_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_31_fu_962_p1() {
    trunc_ln45_31_fu_962_p1 = data_31_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_3_fu_346_p1() {
    trunc_ln45_3_fu_346_p1 = data_3_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_4_fu_368_p1() {
    trunc_ln45_4_fu_368_p1 = data_4_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_5_fu_390_p1() {
    trunc_ln45_5_fu_390_p1 = data_5_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_6_fu_412_p1() {
    trunc_ln45_6_fu_412_p1 = data_6_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_7_fu_434_p1() {
    trunc_ln45_7_fu_434_p1 = data_7_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_8_fu_456_p1() {
    trunc_ln45_8_fu_456_p1 = data_8_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_9_fu_478_p1() {
    trunc_ln45_9_fu_478_p1 = data_9_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_trunc_ln45_fu_280_p1() {
    trunc_ln45_fu_280_p1 = data_0_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_10_fu_512_p1() {
    zext_ln45_10_fu_512_p1 = esl_zext<16,15>(select_ln45_10_fu_504_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_11_fu_534_p1() {
    zext_ln45_11_fu_534_p1 = esl_zext<16,15>(select_ln45_11_fu_526_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_12_fu_556_p1() {
    zext_ln45_12_fu_556_p1 = esl_zext<16,15>(select_ln45_12_fu_548_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_13_fu_578_p1() {
    zext_ln45_13_fu_578_p1 = esl_zext<16,15>(select_ln45_13_fu_570_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_14_fu_600_p1() {
    zext_ln45_14_fu_600_p1 = esl_zext<16,15>(select_ln45_14_fu_592_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_15_fu_622_p1() {
    zext_ln45_15_fu_622_p1 = esl_zext<16,15>(select_ln45_15_fu_614_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_16_fu_644_p1() {
    zext_ln45_16_fu_644_p1 = esl_zext<16,15>(select_ln45_16_fu_636_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_17_fu_666_p1() {
    zext_ln45_17_fu_666_p1 = esl_zext<16,15>(select_ln45_17_fu_658_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_18_fu_688_p1() {
    zext_ln45_18_fu_688_p1 = esl_zext<16,15>(select_ln45_18_fu_680_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_19_fu_710_p1() {
    zext_ln45_19_fu_710_p1 = esl_zext<16,15>(select_ln45_19_fu_702_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_1_fu_314_p1() {
    zext_ln45_1_fu_314_p1 = esl_zext<16,15>(select_ln45_1_fu_306_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_20_fu_732_p1() {
    zext_ln45_20_fu_732_p1 = esl_zext<16,15>(select_ln45_20_fu_724_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_21_fu_754_p1() {
    zext_ln45_21_fu_754_p1 = esl_zext<16,15>(select_ln45_21_fu_746_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_22_fu_776_p1() {
    zext_ln45_22_fu_776_p1 = esl_zext<16,15>(select_ln45_22_fu_768_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_23_fu_798_p1() {
    zext_ln45_23_fu_798_p1 = esl_zext<16,15>(select_ln45_23_fu_790_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_24_fu_820_p1() {
    zext_ln45_24_fu_820_p1 = esl_zext<16,15>(select_ln45_24_fu_812_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_25_fu_842_p1() {
    zext_ln45_25_fu_842_p1 = esl_zext<16,15>(select_ln45_25_fu_834_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_26_fu_864_p1() {
    zext_ln45_26_fu_864_p1 = esl_zext<16,15>(select_ln45_26_fu_856_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_27_fu_886_p1() {
    zext_ln45_27_fu_886_p1 = esl_zext<16,15>(select_ln45_27_fu_878_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_28_fu_908_p1() {
    zext_ln45_28_fu_908_p1 = esl_zext<16,15>(select_ln45_28_fu_900_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_29_fu_930_p1() {
    zext_ln45_29_fu_930_p1 = esl_zext<16,15>(select_ln45_29_fu_922_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_2_fu_336_p1() {
    zext_ln45_2_fu_336_p1 = esl_zext<16,15>(select_ln45_2_fu_328_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_30_fu_952_p1() {
    zext_ln45_30_fu_952_p1 = esl_zext<16,15>(select_ln45_30_fu_944_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_31_fu_974_p1() {
    zext_ln45_31_fu_974_p1 = esl_zext<16,15>(select_ln45_31_fu_966_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_3_fu_358_p1() {
    zext_ln45_3_fu_358_p1 = esl_zext<16,15>(select_ln45_3_fu_350_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_4_fu_380_p1() {
    zext_ln45_4_fu_380_p1 = esl_zext<16,15>(select_ln45_4_fu_372_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_5_fu_402_p1() {
    zext_ln45_5_fu_402_p1 = esl_zext<16,15>(select_ln45_5_fu_394_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_6_fu_424_p1() {
    zext_ln45_6_fu_424_p1 = esl_zext<16,15>(select_ln45_6_fu_416_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_7_fu_446_p1() {
    zext_ln45_7_fu_446_p1 = esl_zext<16,15>(select_ln45_7_fu_438_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_8_fu_468_p1() {
    zext_ln45_8_fu_468_p1 = esl_zext<16,15>(select_ln45_8_fu_460_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_9_fu_490_p1() {
    zext_ln45_9_fu_490_p1 = esl_zext<16,15>(select_ln45_9_fu_482_p3.read());
}

void relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config7_s::thread_zext_ln45_fu_292_p1() {
    zext_ln45_fu_292_p1 = esl_zext<16,15>(select_ln45_fu_284_p3.read());
}

}

